### ISSUE TITLE
Trouver où et comment récupérer les _backstories_

### ISSUE THREAD

**Issue by kaptain-kavern** [Ludeon/RimWorld-fr#146]
Je vais essayer de trouver où ca se passe et comment récupérer une version texte des _backstories_, qui sont encodées "en dur" et pas dans les fichiers XML.

## Pistes/indices
- Voir le mod de Rainbeau/dburgdorf - [Editable Backstories](http://steamcommunity.com/sharedfiles/filedetails/?id=1220862385)

**Comment by kaptain-kavern** [comment]
Je vais m'occuper de cela

**Comment by NeverPire** [comment]
Sinon, éventuellement, tu peux toujours envoyer un message à dburgdorf pour lui demander des infos si tu ne l'as pas déjà fait.

**Comment by b606** [comment]
Bonjour,
avec l'outil de traduction intégré de Ludeon, je pense que cette issue peut être fermée.

**Comment by kiliak** [comment]
Oui
