### ISSUE TITLE
Balise mal formée dans Biomes_Cold.xml

### ISSUE THREAD

**Issue by gcollet** [Ludeon/RimWorld-fr#156]
J'ai corrigé une balise mal fermée dans Biomes_Cold.xml
J'ai push direct sur DevB18, j'espère que j'ai bien géré.

**Comment by gcollet** [comment]
J'ai lancé cette "issue" car je ne vois pas comment discuter d'un commit...

**Comment by NeverPire** [comment]
En mettant un commentaire dessus. De toute manière, je suis alerté directement par mail de toute modification ou message posté sur le répertoire.

**Comment by NeverPire** [comment]
Merci d'avoir corrigé ma gaffe ^^

**Comment by NeverPire** [comment]
Heu, pourquoi tous vos commits sont en double, j'ai du mal à comprendre. 
C'est en lien avec ton merge de bilouweb ?

**Comment by gcollet** [comment]
Oui je pense que j'ai fait une fausse manip avec github

**Comment by gcollet** [comment]
je clos l'issue
