### ISSUE TITLE
Synonymes féminins de Poignardage et de Écrasement

### ISSUE THREAD

**Issue by b606** [Ludeon/RimWorld-fr#179]
Je cherche des synonymes pour ces deux blessures, et on pourrait passer au féminin tout le fichier **DefInjected/HediffDef/Hediffs_Local_Injuries.xml**. Ces (e) partout sont trop laids...

- poignardé, poignardage : blessure au poignard/par arme blanche, ponction, poignardée
- écrasement, broyage, broiement : broyée, écrasée

**Comment by lilidemon** [comment]
Pour "écrasement", "broiement" est le plus proche mais je trouve qu'"écrasement" passe mieux. Ou "compression" ?
Pour "poignardé" : la blessure suivante est "blessure par balles", pourquoi ne pas mettre "blessure par lame/objets tranchants" ou carrément "plaie", ou si ça nous semble trop superficiel, "plaie profonde".

En revanche, pour le féminin, je ne vois pas vraiment comment tu veux faire. A moins d'envisager la phrase ainsi : "[la blessure/morsure/ect] a été bandé." D'ailleurs, je n'aurais pas vu ça avec le verbe être, ça semble bizarre : "[la blessure/morsure/ect] est bandé."

Qu'en penses-tu ?

**Comment by b606** [comment]
Je crois que j'ai trouvé une partie de la solution. J'ai un patch en cours là-dessus mais je préfère attendre que le PR #176 soit validé pour limiter les commits à tester et diminuer les branches.

**Comment by NeverPire** [comment]
Tout d'abord il faut passer "Divers" au féminin. Je propose "Diverses blessures".
J'imagine que tu cherches non seulement des synonymes, mais des synonymes au féminin.
Pour "Poignardé", peut-être "Perforation" ?
En ce qui concerne "Écrasement", je ne vois que "Compression".

**Comment by lilidemon** [comment]
Compression et Perforation vont bien. Bien trouvé ^^
