### ISSUE TITLE
DefInjected/StatCategoryDef/StatCategories.xml <Surgery.label> non traduit

### ISSUE THREAD

**Issue by b606** [Ludeon/RimWorld-fr#182]
DefInjected/StatCategoryDef/StatCategories.xml
<Surgery.label>Surgical</Surgery.label>
A moins que quelqu'un trouve où s'affiche ce tag dans le jeu, on a pour l'instant décidé de le laisse tel quel.

**Comment by NeverPire** [comment]
Logiquement je dirais que ça doit se traduire par Chirurgical mais la majuscule pose question dans ce cas.

**Comment by NeverPire** [comment]
Idem, à fermer je pense.
