### ISSUE TITLE
Traduction de research bench

### ISSUE THREAD

**Issue by Emjay89** [Ludeon/RimWorld-fr#196]
Je me demandais s'il y avait une raison pourquoi "Research bench" a été traduit à "Banc de recherche" quand paillasse serait le mot plus exact ( ou paillasse de recherche).

**Comment by NeverPire** [comment]
Je n'avais jamais réalisé le problème, mais en soit c'est vrai que le mot "banc de recherche" n'existe carrément pas en français. Seul "paillasse de recherche" ou à la limite "poste de recherche" seraient corrects.

**Comment by NeverPire** [comment]
Si on décide de réaliser ce changement, il va falloir faire appel à l'équipe pour utiliser une commande de remplacement parce que ce terme apparaît dans énormément de fichiers.

**Comment by Emjay89** [comment]
Selon moi, ça vaut la peine de faire le changment. Je pourrais faire ça demaine matin avec la commande de recherche.

**Comment by NeverPire** [comment]
Au passage, si quelqu'un pouvait se donner la peine de m'expliquer comment utiliser ce genre de commande, ce serait génial. Je galère prodigieusement à apprendre ça en autodidacte.

**Comment by Emjay89** [comment]
J’utilise Visual Studio Code pour faire mes changements et la fonction “recherche et remplacement” est le 2e onglet à gauche de la fenêtre principale.

**Comment by NeverPire** [comment]
Donc tu ne passes pas par GitHub Desktop ou Git CMD. Je devrais peut-être faire pareil. Merci !

**Comment by Emjay89** [comment]
Oui je vais vérifier ces changements aussi.

J'ai aucune idée des différences entre GitHub Desktop, Git CMD et Visual Studio Code pcq j'ai jamais utilisé ces deux premiers mais vs code m'a jamais donné de problèmes! Je te suggère de le télécharger et l'essayer un peu pour voir comment t'aimes ça.

**Comment by Emjay89** [comment]
J'ai utilisé la fonction "find and replace" pour HIS et HISCAP alors il est possible que j'ai modifiée des choses dans la section "unused" mais autrement je ne crois pas avoir touché à cette section. 
Ce que j'ai observé par contre c'est qu'il y a beaucoup de backstories avec une traduction un peu boiteuse et qu'il manque un peu de d'uniformité dans les choix de traduction ( research bench était traduit comme banc de recherche, atelier de recherche et établi de recherche). Alors il faudra repasser toute la traduction un jour pour faire les mêmes choix de traduction partout.

**Comment by boundir** [comment]
J'avais déjà effectué le Recherche et Remplace dans un précédent commit pour les HIS HE etc... https://github.com/Ludeon/RimWorld-fr/commit/679898559727fbe9f71129d3ec5e064eabc7cf6d
C'est pour ça que le seul fichier où tu as trouvé des références est celui que j'ai marqué en DEPRECATED.

**Comment by NeverPire** [comment]
B18 n'utilise aucune de ces syntaxes. Elles ont toutes été implémentées dans la version 1.0.

J'ai personnellement réalisé quelque chose comme la moitié des traductions actuelles des backstories et ça m'a pris des jours. Le travail de relecture sera conséquent quand on s'y mettra. Avant tout, il faut traduire ce qui ne l'est pas encore.

**Comment by NeverPire** [comment]
Les HECAP étaient par contre toujours présents boundir.

**Comment by boundir** [comment]
Juste pour le fichier Backstories noté DEPRECATED.

**Comment by NeverPire** [comment]
Oui exactement. Je mettais justement en lumière l'inutilité de garder des fichiers compatibles avec les anciennes versions.
