### ISSUE TITLE
Mise à jour des fichiers de traductions pour la version 1.0

### ISSUE THREAD

**Issue by boundir** [Ludeon/RimWorld-fr#197]
Comme vous le savez, les fichiers de traductions ont changé par rapport à la dernière version du jeu.

A cet effet @Philou95 a fait un travail remarquable en allant chercher l'ensemble des modifications apportées. Seulement, certaines lui ont échappé ou peut-être n'avait-il pas finit son travail. Voici les anomalies que j'ai pu rencontrer [Pastebin](https://pastebin.com/ukK3PbXt) (je ne crois pas avoir demandé une durée illimité, j'ajouterai le fichier en pièce jointe par la suite :+1:). 
Entre temps les équipes de développement de RimWorld ont mit en place un outil permettant de reporter ces modifications, formater correctement le nom des nouvelles balises, et placer le mot clé "TODO" sur les traductions manquantes avec au dessus la version originale.
Exemple:
```xml
  <!-- EN: hoof -->
  <Hoof.label>TODO</Hoof.label>
```

J'ai pris la liberté de déployer les fichiers formatés par l'outil et d'y apporter les traductions réalisées sur la branche "Maj-1.0" sur un fork. Si ces modifications vous conviennent je les déploierai ensuite sur la branche master.

En attente de vous lire.

**Comment by b606** [comment]
PS: les deux branches master et MAJ1.0 sont aussi en conflit sur presque toutes les Keyed/*.xml
La priorité est peut-être de résoudre tous ces conflits avant toute chose
J'en suis à Keyed/Letters.xml dans cette liste...

Keyed/Alerts.xml
Keyed/Credits.xml
Keyed/Dates.xml
Keyed/Designators.xml
Keyed/Dialog_StatsReports.xml
Keyed/Dialog_Trees.xml
Keyed/Dialogs_Various.xml
Keyed/Enums.xml
Keyed/FloatMenu.xml
Keyed/GameplayCommands.xml
Keyed/Grammar.xml
Keyed/ITabs.xml
Keyed/Incidents.xml
Keyed/Letters.xml
Keyed/MainTabs.xml
Keyed/Menu_KeyBindings.xml
Keyed/Menu_Options.xml
Keyed/Menus_Main.xml
Keyed/Messages.xml
Keyed/Misc.xml
Keyed/Misc_Gameplay.xml
Keyed/PlayInterface.xml
Keyed/ScenParts.xml
Keyed/Skills.xml
Keyed/Time.xml
Keyed/WITabs.xml
Keyed/WorkTags.xml

**Comment by boundir** [comment]
Salut @b606, je t'explique le pourquoi des conflits:

J'ai repris les fichiers de la branche master et les ai copié dans le répertoire du jeu. J'ai ensuite utilisé l'outil de traduction qui m'a reformaté les fichiers.  Ces derniers ont été poussés sur la branche master, ce qui explique tous les conflits entre master et Maj-1.0
Par la suite j'ai regardé un à un les 100+ fichiers de la branche Maj-1.0 pour reprendre les traductions qui n'étaient pas encore présentes dans la branche master.

Je te propose de prendre en compte mon rapport sur la branche Maj-1.0 pour réaliser qu'on n'était pas encore au point par rapport à ce qui est attendu.
[maj-1.0____master.txt](https://github.com/Ludeon/RimWorld-fr/files/2216270/maj-1.0____master.txt)

Je vais envoyer un PR comprenant plusieurs commit, ceux-ci reprenant les modifs présentes dans Maj-1.0. Merci d'y jeter un œil pour qu'on puisse valider dès ce soir. Il serait également intéressant de ne pas faire de nouveau commit avant de l'avoir validé.

**Comment by boundir** [comment]
On en parlait avec Tynan dernièrement, l'idéal serait de ne plus travailler en Pull Request. Tout devrait se faire sur le master. Un fichier, un commit/push.
Pour le coup c'était uniquement parce que cette modification devait toucher de multiples fichiers.

**Comment by b606** [comment]
J'ai vu la discussion là-dessus sur le forum, mais çà me gêne un peu car une fois poussé dans le master le seul backup c'est un git revert. Au moins avec un PR on peut vérifier, tester dessus et peaufiner (le git est directement branché sur le jeu chez moi dans Core/Mods/Language:Rimworld-fr)

**Comment by boundir** [comment]
Oui et non un git revert c'est plus pour un commit qui planterait ton programme et t'obligerait à faire machine arrière. Ici ce n'est que du texte. 
Si tu vois un commit qui traduit "Free" par "Gratuit" au lieu de "Libre" par exemple. Tu n'as qu'à faire un autre commit par la suite en mettant "Gratuit". Tu peux également ouvrir une issue sur GitHub en taguant la personne qui a fait le commit pour que vous puissiez en discuter.

**Comment by b606** [comment]
Si, si, il y a bien des modifs qui plantent le jeu : j'ai eu le cas lundi quand j'étais encore en B18. Surtout les rulepack et logentry + les générations des noms de régions du monde étaient plantés (800 méga de log et des plombes à charger le jeu). Tout le monde s'appelait ""ErrorName" et les plaines ou montagnes "Could not resolve qqchose"

**Comment by b606** [comment]
Et les aptitudes s'appelaient tous "Tir" :-)

**Comment by Philou95** [comment]
A mon avis vu toute les modifs du nombre d'argument ou de nom de balise, les traduction ne sont pas compatible entre la beta et la v1.

**Comment by b606** [comment]
J'ai poussé un soupir de soulagement quand j'ai vu les nouvelles branches que vous avez mis en place ici. Bon boulot les gars !

**Comment by boundir** [comment]
Ça sera pas le même type de soupir quand il faudra s'attaquer aux Backstories haha. Je vais d'ailleurs ajouter l'ancien fichier en lui mettant une extension OLD ou DEPRECATED. C'est juste histoire d'avoir du texte traduit qui peut peut-être servir.

**Comment by NeverPire** [comment]
Malheureusement je ne crois pas :/
Ou alors peut-être dans les titres si l'on en décide ainsi, mais les féministes vont hurler.
Juste pour ergoter, les "son/sa" n'ont jamais posé problème, on n'est pas en anglais ;-)

J'avais essayé de jouer à la version 1.0 en utilisant la traduction de DevB18.
Le jeu tournait sans cracher, mais j'avais des erreurs toutes les 5 secondes et tous les opposants et leurs factions s'appellaient ErrorName, ainsi que les régions du monde.

En désactivant le mode développeur, ça marchait toujours, mais les ErrorName restaient.

**Comment by boundir** [comment]
Oui les balises ont changé entre B18 et ~1.0. On n'est pas utiliser la trad B18 dans ~1.0 et inversement.

**Comment by NeverPire** [comment]
Bon, si tous ces outils fonctionnent, il va me falloir une sérieuse mise à jour, moi.

**Comment by b606** [comment]
J'ai remis un peu à jour le FAQ du wiki. Il y a certainement des choses encore à améliorer...

**Comment by kiliak** [comment]
Salut à tous j'ignore si vous recevrez une notification pour ce message, une nouvelle mise à jour 1.1 vient de sortir s'il y a quelq'un de plus competent que moi pour créer une nouvelle branche je me lancerais dans la trad.
