### ISSUE TITLE
Keyed DialogVarious.xml et Alerts.xml dans Maj1.0 ; traductions non reportées sur le master.

### ISSUE THREAD

**Issue by NeverPire** [Ludeon/RimWorld-fr#200]
Tout est dans le titre.

**Comment by b606** [comment]
Les keyed, et notamment DialogVarious j'ai déjà un truc mais il faut que je finisse ma liste de merge

**Comment by NeverPire** [comment]
Ah ok.
J'ai corrigé une petite faute directement dans Patch 1 pour que la correction soit directement intégrée quand vous appliquerez vos algorithmes.

**Comment by boundir** [comment]
On ne devrait plus toucher à Patch 1. Uniquement master.

**Comment by NeverPire** [comment]
J'allais oublier cette faute si je ne faisais rien.

**Comment by boundir** [comment]
Ok je vois de quoi tu voulais parler maintenat @NeverPire. Je t'avoue que c'est un des fichiers qui m'a fait le plus mal au crâne.
```xml
<!-- EN: Armor penetration -->
<ArmorPenetration>Armure pénétration</ArmorPenetration>
<!-- EN: Direct hit chance -->
<DirectHitChance>Chance de touché direct</DirectHitChance>
<!-- EN: Tameness will never decay. -->
<TamenessWillNotDecay>Les animaux apprivoisés ne pourrissent jamais.</TamenessWillNotDecay>
```
C'est pour cela que pas mal de traductions ont été abandonnées. J'espère que @b606 nous réserve une super surprise :+1:

**Comment by NeverPire** [comment]
Une fois cela fait, b606, ferme ce PR en demandant l'accord de philou si tu le veux bien.
Je ne supprimerai pas la branche et la laisserai à disposition pour quiconque veut jeter un coup d'oeil à l'une ou l'autre traduction humaine ou google.
