### ISSUE TITLE
[v1.0] Liste des fichiers à traduire

### ISSUE THREAD

**Issue by boundir** [Ludeon/RimWorld-fr#201]
Merci de cocher le fichier une fois traité.
Pour trouver les lignes nécessitant une traduction recherchez simplement `TODO` dans le fichier.

- [x] \DefInjected\BodyDef\Bodies_Mechanoid.xml
- [x] \DefInjected\BodyPartDef\BodyParts_Animal.xml
- [x] \DefInjected\BodyPartDef\BodyParts_Mechanoid.xml
- [x] \DefInjected\BodyPartGroupDef\BodyPartGroups.xml
- [x] \DefInjected\ConceptDef\Concepts_NotedOpportunistic.xml
- [x] \DefInjected\DamageDef\Damages_Misc.xml
- [x] \DefInjected\FactionDef\Factions_Misc.xml
- [x] \DefInjected\HediffDef\Hediffs_Global_Temperature.xml
- [x] \DefInjected\HediffDef\Hediffs_Local_AddedParts.xml
- [x] \DefInjected\HediffDef\Hediffs_Local_Infections.xml
- [x] \DefInjected\HediffDef\Hediffs_Local_Injuries.xml
- [x] \DefInjected\HediffGiverSetDef\HediffGiverSets.xml
- [x] \DefInjected\HistoryAutoRecorderDef\HistoryAutoRecorders.xml
- [x] \DefInjected\HistoryAutoRecorderGroupDef\HistoryAutoRecorderGroups.xml
- [x] \DefInjected\IncidentDef\Incidents_Map_Disease.xml
- [x] \DefInjected\IncidentDef\Incidents_Map_Misc.xml
- [x] \DefInjected\IncidentDef\Incidents_Map_Threats.xml
- [x] \DefInjected\IncidentDef\Incidents_World_Quests.xml
- [x] \DefInjected\JobDef\Jobs_Joy.xml
- [x] \DefInjected\JobDef\Jobs_Misc.xml
- [x] \DefInjected\JobDef\Jobs_Work.xml
- [x] \DefInjected\JoyKindDef\JoyKinds.xml
- [x] \DefInjected\KeyBindingDef\KeyBindings.xml
- [x] \DefInjected\NeedDef\Needs.xml
- [x] \DefInjected\PawnCapacityDef\PawnCapacity.xml
- [x] \DefInjected\PawnColumnDef\PawnColumns_Checkbox.xml
- [x] \DefInjected\PawnColumnDef\PawnColumns_Misc.xml
- [x] \DefInjected\PawnKindDef\PawnKinds_Tribal.xml
- [x] \DefInjected\PawnsArrivalModeDef\PawnsArrivalModes.xml
- [x] \DefInjected\RecipeDef\Recipes_Production.xml
- [x] \DefInjected\RecipeDef\Recipes_Surgery_Installations.xml
- [x] \DefInjected\RoomStatDef\RoomStats.xml
- [ ] DefInjected/RulePackDef/RulePacks_DamageEvent.xml (EDIT: ajouté 30/09/2018)
- [x] \DefInjected\RulePackDef\RulePacks_Combat.xml
- [x] \DefInjected\RulePackDef\RulePacks_Global.xml
- [x] \DefInjected\RulePackDef\RulePacks_Maneuvers.xml
- [x] \DefInjected\ScenarioDef\Scenarios_Classic.xml
- [x] \DefInjected\ScenPartDef\ScenParts_Various.xml
- [x] \DefInjected\SitePartDef\Manhunters.xml
- [x] \DefInjected\SitePartDef\Outpost.xml
- [x] \DefInjected\SitePartDef\SleepingMechanoids.xml
- [x] \DefInjected\SitePartDef\Turrets.xml
- [x] \DefInjected\SpecialThingFilterDef\SpecialThingFilters.xml
- [x] \DefInjected\StatDef\Stats_Apparel.xml
- [x] \DefInjected\StatDef\Stats_Basics_General.xml
- [x] \DefInjected\StatDef\Stats_Basics_Special.xml
- [x] \DefInjected\StatDef\Stats_Building_Special.xml
- [x] \DefInjected\StatDef\Stats_Pawns_Combat.xml
- [x] \DefInjected\StatDef\Stats_Pawns_General.xml
- [x] \DefInjected\StatDef\Stats_Pawns_WorkRecipes.xml
- [x] \DefInjected\StatDef\Stats_Weapons_Melee.xml
- [x] \DefInjected\StatDef\Stats_Weapons_Ranged.xml
- [x] \DefInjected\TaleDef\Tales_DoublePawn.xml
- [ ] DefInjected/TaleDef/Tales_Caravan.xml
- [x] DefInjected/TaleDef/Tales_Event.xml
- [ ] DefInjected/TaleDef/Tales_Health.xml
- [ ] DefInjected/TaleDef/Tales_Incident.xml
- [x] DefInjected/TaleDef/Tales_Job.xml
- [x] \DefInjected\TerrainDef\Terrain_Natural.xml
- [x] \DefInjected\TerrainDef\Terrain_Special.xml
- [x] \DefInjected\TerrainDef\Terrain_Water.xml
- [x] \DefInjected\ThingCategoryDef\ThingCategories.xml
- [x] \DefInjected\ThingDef\Alcohol_Beer.xml
- [x] \DefInjected\ThingDef\Apparel_Various.xml
- [x] \DefInjected\ThingDef\Buildings_Furniture.xml
- [x] \DefInjected\ThingDef\Buildings_Joy.xml
- [x] \DefInjected\ThingDef\Buildings_Power.xml
- [x] \DefInjected\ThingDef\Buildings_Production.xml
- [x] \DefInjected\ThingDef\Buildings_Security.xml
- [x] \DefInjected\ThingDef\Ethereal_Various.xml
- [x] \DefInjected\ThingDef\ImpliedDefs.xml
- [x] \DefInjected\ThingDef\Items_BodyParts.xml
- [x] \DefInjected\ThingDef\Items_Resource_Stuff.xml
- [x] \DefInjected\ThingDef\Items_Unfinished.xml
- [x] \DefInjected\ThingDef\Plants_Cultivated_Farm.xml
- [x] \DefInjected\ThingDef\Races_Animal_Arid.xml
- [x] \DefInjected\ThingDef\Races_Animal_Bears.xml
- [x] \DefInjected\ThingDef\Races_Animal_Birds.xml
- [x] \DefInjected\ThingDef\Races_Animal_Farm.xml
- [x] \DefInjected\ThingDef\Races_Animal_Insect.xml
- [x] \DefInjected\ThingDef\Races_Animal_Pet.xml
- [x] \DefInjected\ThingDef\Races_Animal_Temperate.xml
- [x] \DefInjected\ThingDef\Races_Animal_Tropical.xml
- [x] \DefInjected\ThingDef\Races_Mechanoid.xml
- [x] \DefInjected\ThingDef\Various_Stone.xml
- [x] \DefInjected\ThoughtDef\Thoughts_Memory_Misc.xml
- [x] \DefInjected\ThoughtDef\Thoughts_Situation_Needs.xml
- [x] \DefInjected\ThoughtDef\Thoughts_Situation_Social.xml
- [x] \DefInjected\ThoughtDef\Thoughts_Situation_Special.xml
- [x] \DefInjected\ThoughtDef\Thoughts_Situation_Traits.xml
- [x] \DefInjected\TrainableDef\Trainables.xml
- [x] \DefInjected\TraitDef\Traits_Singular.xml
- [x] \DefInjected\TraitDef\Traits_Spectrum.xml
- [x] \DefInjected\TransferableSorterDef\TransferableSorters.xml
- [x] \DefInjected\WorkGiverDef\WorkGivers.xml
- [x] \DefInjected\WorkTypeDef\WorkTypes.xml
- [x] \Keyed\Dialog_Trees.xml
- [x] \Keyed\Dialogs_Various.xml
- [x] \Keyed\Enums.xml
- [x] \Keyed\FloatMenu.xml
- [x] \Keyed\GameplayCommands.xml
- [x] \Keyed\Incidents.xml
- [x] \Keyed\Letters.xml
- [x] \Keyed\MainTabs.xml
- [x] \Keyed\Menu_Options.xml
- [x] \Keyed\Menus_Main.xml
- [x] \Keyed\Messages.xml
- [x] \Keyed\Misc_Gameplay.xml
- [x] \Keyed\ScenParts.xml
- [x] \Keyed\WITabs.xml

**Comment by NeverPire** [comment]
C'est plus pratique que notre ancienne version qui utilisait les ~~ pour barrer les fichiers traduits, 
je dois bien le reconnaître. ~Bon, on ne va pas s'ennuyer avec tout ça.~

**Comment by Nibsy** [comment]
Salut, j'ai modifié le fichier "\DefInjected\TraitDef\Traits_Singular.xml". Je l'ai soumis directement sur la branche existante, et je voulais savoir si j'aurais dû le soumettre d'abord à un pull request (comme ça je saurai la prochaine fois). Merci :)

**Comment by kiliak** [comment]
perso je ne fais des pull request que si j'ai un doute sur ce que je fais. de toute façon ceux qui maitrise bien la technique repasse derrière.
enfin vu mon niveau je devrais sans doute en faire plus ;)
par contre une question on utilise la branche Maj-1.0 comme Nibsy ou on va direct sur le master comme le suggérait Tynan.

**Comment by b606** [comment]
@Nibsy, j'ai mis les modifications qui étaient sur la branche MaJ1.0 dans la branche master.

@kiliak, mets un PR pour DefInjected/ThingDef/Items_BodyParts.xml si tu a besoin de révision. Les noms des objets dans DefInjected/ThingDef/ImpliedDefs.xml auraient aussi besoin d'être uniformisés dans plusieurs fichiers.

**Comment by kiliak** [comment]
Pour l'uniformisation ça va être long, ils y a beaucoup de fichiers, et pas toujours les même traducteurs. 

Exemple les" tourelles Sniper"  dans l'onglet Recherche, que moi j'ai converti par "tourelle tireur d'élite " dans ce fichier ( que je devrais plutôt converir en" de précision "ou" longue portée." )
Ou Archotect que moi j'ai gardé faute d'équivalent fr

**Comment by Nibsy** [comment]
Encore une question : j'ai cru comprendre qu'on ne mettait jamais de majuscules en début de phrase, mais je vois parfois des majuscules dans le texte anglais. Dans ce cas, faut-il mettre en minuscule quand même ou se calquer sur l'anglais ?

**Comment by kiliak** [comment]
Moi je me calque sur l'anglais par défaut. Je rectifirais plus tard si besoin

**Comment by b606** [comment]
Petit récapitulatif, nombre de TODO restants
  - Keyed + Definjected : 188 (sur 743 au début)
  - Backstories : 2043 (sur 2043 au début)
Çà avance !

**Comment by kiliak** [comment]
👍

**Comment by b606** [comment]
Keyed + Definjected : 78 (sur 743 au début)

**Comment by thelimp** [comment]
Salut a tous,

J'ai fait DefInjected/RulePackDef/Interactions_Prisoner.xml

Je découvre GitHub, j’espère avoir fait les choses correctement :)

**Comment by kiliak** [comment]
salut, et merci de venir faire joujou avec nous ;)

 perso j'ai beaucoup de mal avec le dossier RulePackDef ce sera plutôt b606 qui pourra te dire ça par contre je ne vois pas de modifs sur ces fichiers, tu les as poussé sur le master ou fait unPullRequest? ...en même temps je suis pas doué!

**Comment by kiliak** [comment]
Aïe,  je ne pourrais pas te dire j'suis nul avec github. 

Par contre si c'est un problème  de droit j'ai eu quelque chose de semblable: regardes si tu as une ligne jaune en haut de github qui parle de "membre" pour finaliser l'inscription,sans ça je ne pouvais pas agir sur le Master. 

 Sinon cherche à faire "un pull request" ça permet de faire des propositions de modif que les autres menbres peuvent regarder sans que ça touche au master.

**Comment by b606** [comment]
Bienvenu @thelimp !
Si tu n'arrives pas à pousser sur master, utilise le Pull Request comme le suggère kiliak.

**Comment by thelimp** [comment]
Merci !
J'ai tenté un Pull Request, voici sa réponse : 
![image](https://user-images.githubusercontent.com/41955403/43519361-69c84858-958f-11e8-9a99-e9245e958898.png)
et lorsque je Push Commit : 
![image](https://user-images.githubusercontent.com/41955403/43519388-87482696-958f-11e8-9c6e-6ef6a8a4b48f.png)

**Comment by b606** [comment]
Je n'utilise pas Github desktop parce qu'il n'y a pas de version pour ma machine. Il faudrait l'aide de quelqu'un qui l'utilise pour te dépanner.
Comment a été crée ton repository local ? Je demande çà parce qu'en général ta branche master devrait avoir en mémoire qu'elle vient de la branche remotes/upstream/master (de Ludeon/Rimworld-fr)

**Comment by thelimp** [comment]
de cette facon : 
![image](https://user-images.githubusercontent.com/41955403/43520056-ef85c5b8-9591-11e8-93cb-0c3bab62deed.png)

**Comment by b606** [comment]
OK c'est un git clone. Tu as quoi comme liste de branches dans ce git ?

**Comment by boundir** [comment]
Salut @thelimp, je ne te trouve pas dans la liste des membres sur ce repo. As-tu bien reçu une confirmation comme quoi tu étais intégré à l'équipe?

**Comment by thelimp** [comment]
@boundir ...ha oui c'est probablement ça le problème ^^

**Comment by b606** [comment]
J'ai testé avec l'outil de traduction Ludeon. A part quelques changements de l'anglais que j'ai dû signaler par des TODO, il y a aussi un changement de nombre d'arguments dans le texte : 
(Je resignale ici pour ne pas oublier)

- [ ] AnimalsSkillTooLow (FloatMenu.xml:84)
  - 'animals skill too low - need {0}'
  - 'compétence avec les animaux trop faible'
- [ ] RefugeeChasedInitial (Incidents.xml:133)
  - 'A [PAWN_title] named [PAWN_nameDef] calls you from nearby. [PAWN_pronoun] is being chased by {2} from {3}!\n\n[PAWN_pronoun] begs for safety and offers to join your colony. [PAWN_pronoun] tells you [PAWN_pronoun] is {4} years old, but there's no time to collect more information.\n\nBe warned - if you accept, you'll have to fight off the {2} on [PAWN_possessive] tail. Their group is composed of:\n\n{5}'
  - 'Un [PAWN_title] nommé [PAWN_nameDef] vous appelle. [PAWN_pronoun] est pourchassé(e) par des {2} de {3} !\n\n[PAWN_pronoun] vous supplie de l'aider et de rejoindre votre colonie. [PAWN_pronoun] a {4} ans biologiques.\n\nAttention : si vous acceptez, vous devrez combattre les {2} à ses trousses.'
- [ ] CaravanRequestInfo (Incidents.xml:217)
  - 'Requesting: {0} ({3}), Reward: {1} ({4}) ({2} left)'
  - 'Demande : {0}, Récompense : {1} (manquent {2})'
- [ ] NewDisease (Letters.xml:69)
  - '{0} has gotten sick from {1}.\n\nEnsure you have a medical bed and a doctor. Make sure that {2} gets proper treatment and spends as much time in bed as possible.'
  - '{1} a rendu malade {0}.\n\nAssurez-vous de disposer d'un lit médical et d'un docteur, et que {0} bénéficie d'un traitement adéquat et reste alité autant de temps que possible.'
- [ ] LetterLeadersDeathLabel (Letters.xml:118)
  - '{1} died: {0}'
  - 'Mort d'un chef'
- [ ] LetterAcceptedProposal (Letters.xml:186)
  - 'At some point in the coming days or quadrums, they will have their marriage ceremony and invite all the colonists. Consider placing a marriage spot if you want to control where the ceremony occurs.'
  - '{1} a accepté la demande en mariage de {0}. À un moment dans les jours ou les saisons à venir, ils organiseront leur cérémonie de mariage à laquelle ils inviteront tous les colons. Envisagez le placement d'une zone de mariage si vous voulez choisir l'endroit où la cérémonie se tiendra.'
- [ ] LetterRejectedProposal (Letters.xml:188)
  - '{0} is going to be unhappy about this.'
  - '{1} a refusé la demande de mariage de {0}. Cela va rendre {0} malheureux.'
- [ ] TranslationThanks (Menus_Main.xml:60)
  - 'All translations of RimWorld are fan-made. This fan-made translation was created by the following excellent volunteers:\n\n{0}'
  - 'Toutes les traductions de RimWorld sont faites par des fans. Cette traduction a été créée par les supers fan-bénévoles suivants.'
- [ ] MessageAnimalsGoPsychoHunted (Messages.xml:61)
  - 'Warning: {0} have a {1} chance to attack when harmed from rifle range. Chance is higher if closer, less with good hunter stealth.'
  - 'Attention : les {0} risquent d'attaquer si vous les blessez.'
- [ ] DrugEffectMultiplier (Misc_Gameplay.xml:204)
  - '{0} effect multiplier: {1}'
  - 'Facteur d'effet de {0}'
- [ ] QuestTargetDestroyInspectString (Misc_Gameplay.xml:266)
  - '{0} wants this destroyed.\n    Reward: {1} ({2})'
  - '{0} veut que cela soit détruit.\n    Récompense : {1}.'
- [ ] ItemStashContents (Misc_Gameplay.xml:270)
  - 'Contents: {0} ({1})'
  - 'Contenus : {0}.'
- [ ] ShellLoaded (Misc_Gameplay.xml:454)
  - 'Shell loaded: {0}'
  - 'Obus chargé'

**Comment by b606** [comment]
Les gars et filles :
Keyed + Definjected : 46 (sur 743 au début)

**Comment by kiliak** [comment]
Ça avance , ça avance ! Espérons qu'ils arrêtent de modifier les textes sans arrêt  😉
Sinon aurait tu la possibilité  de lister les fichiers restant avec des TODO, je suis obligé  d'éplucher les fichiers un a un,... pépé  à du mal avec les éditeurs de texte 😅

**Comment by b606** [comment]
Ci dessous les TODO que j'ai
- [ ] Keyed/Dialog_StatsReports.xml
- [ ] Keyed/Dialogs_Various.xml
- [ ] Keyed/FloatMenu.xml
- [ ] Keyed/ITabs.xml
- [ ] Keyed/Letters.xml
- [ ] Keyed/Messages.xml
- [ ] DefInjected/RulePackDef/RulePacks_Combat.xml
- [ ] DefInjected/RulePackDef/RulePacks_Global.xml
- [ ] DefInjected/RulePackDef/RulePacks_Maneuvers.xml
- [ ] DefInjected/RulePackDef/RulePacks_Namers_Animals.xml
- [ ] DefInjected/RulePackDef/RulePacks_Namers_Factions.xml
- [ ] DefInjected/RulePackDef/RulePacks_Namers_WorldFeatures.xml
- [ ] DefInjected/StatDef/Stats_Pawns_WorkGeneral.xml
- [ ] DefInjected/TaleDef/Tales_Incident.xml
- [ ] DefInjected/ThingDef/ImpliedDefs.xml
- [ ] DefInjected/ThingDef/Items_Resource_Stuff.xml
- [ ] DefInjected/ToolCapacityDef/ToolCapacity.xml

**Comment by kiliak** [comment]
merci.
bon j'ai toujours autant de mal avec les rulepack mais j'vais étudier ça, il faudra bien en venir a bout.

**Comment by b606** [comment]
Les gars et filles, on est à
   Keyed + Definjected : 5 TODO (sur 743 au début)

EN fait 20, mais 15 sont dans les RulePacks qui sont essentiellement des commentaires pour vérification et je les décoche de la liste ci-dessus. Les 5 autres : 
  - un dans DefInjected/TaleDef/Tales_Incident.xml
  - j'ai rajouté 1 par fichier dans les InteractionDef qui sont incomplets.

Dans les RulePacks, il devrait rester les RulePacks_Art*

@thelimp , il ne faut pas changer le nom de smokeleaf, yayo, go-juice etc parce qu'on avait déjà eu une discussion dessus pour les garder tels quels, en les laissant dans l'univers RimWorld. Pour chemfuel, la traduction par "essence" sonne aussi un peu décalée ("fuel"?, on avait buté dessus et laissé chemfuel en attendant mieux).

**Comment by kiliak** [comment]
J'ai vu, mais j'y touche pas, je ne comprend pas du tout comment agencer les fichiers:

Je n'arrive pas trop à voir comment écrire les phrases avec les termes entre [ ],
 Ni ou écrire ces phrases phrases une fois traduites, 
ni ce qu'il faut écrire entre les < >.

 ...Bref je narrive juste qu' à remplacer les >TODO< par du bon vieux français 😊

Du coup je me suis mis sur les backstories et même là j'suis emmerdé  avec les [ ]😅

**Comment by thelimp** [comment]
@b606 : J'ai eu un échange avec @kiliak a ce propos, ma question est : est ce que je dois annuler mes propositions de modifications ou les recorriger ?

**Comment by b606** [comment]
@thelimp  tu as des bonnes modifs dans la liste des commits. Refais  juste un commit qui remplace les termes en questions

**Comment by b606** [comment]
Oups, repondu trop tard :-)

**Comment by b606** [comment]
Un petit point sur l'état actuel de la traduction : 
- Il nous reste les trois fichiers TaleDef/Tales_Caravan.xml, Tales_Health.xml, et Tales_Incident.xml
- Backstories : 1354 (sur 2043 au début)
:smile:

**Comment by b606** [comment]
Backstories : 705 (sur 2043 au début) :+1:

**Comment by kiliak** [comment]
tout çà prend forme.

**Comment by b606** [comment]
Un petit point sur la trad : 
1. Les TODO dans DefInjected :
- [ ] DefInjected/RulePackDef/RulePacks_DamageEvent.xml
- [ ] DefInjected/TaleDef/Tales_Health.xml
- [ ] DefInjected/TaleDef/Tales_Incident.xml
- [ ] DefInjected/TaleDef/Tales_Job.xml
- [ ] DefInjected/ThingDef/Apparel_Belts.xml
2. Une vingtaine d'arguments {...} à changer
3. Backstories :  : 202 (sur 2043 au début) :+1:

**Comment by kiliak** [comment]
Voilà on a fini les backstories !!! Il reste 6 TODO dans le fichier pour des termes à peaufiner.

si quelqu'un a le courage de repasser derrière, il y a surement des fautes et des tournures de phrase a reprendre. (j'vais repasser dessus aussi mais un œil extérieur c'est mieux)

moi j'vais boire une bière...ou deux .

pour info la version1.0 officiel du jeu sera mise en ligne dans quelques jours.

**Comment by Nibsy** [comment]
Bonjour, je viens de survoler les backstories, et j'ai remarqué certaines descriptions entièrement au masculin, alors que d'autres non. Par exemple "était le seul survivant" ou "était passager". Faut-il modifier ces passages ?

**Comment by Nibsy** [comment]
OK je vais y jeter un oeil plus sérieux alors :)

**Comment by b606** [comment]
Il y a toutes ces relectures mais "Tchin" quand même :cocktail: :cocktail: :cocktail: :beer:

**Comment by NeverPire** [comment]
C'est moi qui avait traduit la majorité des backstories à l'époque avec notamment ce fameux problème du masculin/féminin donc j'aurai facile à aller les corriger.
