### ISSUE TITLE
BodyParts_Mechanoid.xml

### ISSUE THREAD

**Issue by kiliak** [Ludeon/RimWorld-fr#202]
Dans ce fichier il y a "fluide reprocessor", je ne trouve pas de correspondance sur le net. Je ne sais pas s'il parle d'un liquide (huile), ou'd'une pièce genre la pompe (coeur).
J'ai mis huile hydraulique mais plus j'y pense et plus je penche pour la pompe.
Une idée ?

**Comment by Emjay89** [comment]
Je crois que ça serait plus comparable à un rein ou au foie. « Appareil de traitement des fluides usés » serait apte, mais c’est loooooong.

**Comment by Emjay89** [comment]
Je suis d'accord avec filtre à huile ou bien processeur hydraulique. En fin de compte, "Fluid reprocessor" est quand même un pièce mécanique inventée! Faudrais pas trop se casser la tête.

**Comment by kiliak** [comment]
Processeur hydrolique! Pour le fun,  ça fait pièce super technique 😃

**Comment by kiliak** [comment]
Mouai on peut l'écrire comme ça aussi😇

**Comment by b606** [comment]
J'ai mis dans le master la modif pour l'instant.
