### ISSUE TITLE
abscence des {0} et {1} dans les trads

### ISSUE THREAD

**Issue by kiliak** [Ludeon/RimWorld-fr#205]
j'ai trouvé plusieurs fichiers dans les quels {0} et {1} n’étaient pas incorporés dans les traductions en francais, je les ai rajouté mais il y a peut être une raison pour ça?

**Comment by b606** [comment]
Dans quel fichier est-ce ?
Si c'est dans les Keyed #204  c'est déjà fait, ou dans les fichiers cochés au #201 même si çà n'apparait pas encore dans le master.

Vérifie en premier la liste des fichiers ici https://github.com/Ludeon/RimWorld-fr/pull/204/files
et modifie directement dedans si besoin.

**Comment by kiliak** [comment]
c'était sur le master 
DefInjected/SitePartDef/Turrets.xml
DefInjected/sitePartDef/SleepingMechanoids.xml
deflInjected/SitePartDef/Outpost.xml
DefInjected/SitePartDef/Manhunters.xml

sauf erreur j'ai fait les rectifs. je vérifie #204

**Comment by b606** [comment]
Je viens de fusionner master dans 204. Ils doivent y être.

**Comment by b606** [comment]
Si tout est Ok on ferme cette issue.
