### ISSUE TITLE
Traduction de RulePacks_Namers_WorldFeatures.xml

### ISSUE THREAD

**Issue by b606** [Ludeon/RimWorld-fr#210]
Quand vous avez le temps, jetez un petit coup d'oeil sur
https://github.com/Ludeon/RimWorld-fr/edit/master/DefInjected/RulePackDef/RulePacks_Namers_WorldFeatures.xml
et proposez des termes.

C'est les noms de régions que vous voyez dans l'écran Monde.

**Comment by Emjay89** [comment]
Voulais-tu qu'on fasse les changements directement dans le fichier ou les proposer ici?

**Comment by b606** [comment]
Allez-y pour les modifications. Vérifiez simplement que çà donne quelque chose de correcte dans le jeu

**Comment by Emjay89** [comment]
Excellent! En effet..... "reach" est enmerrdant à traduire...... Ça a été traduit à "bief" and Le trône de fer mais c'est carrément pas la même chose!
En passant, je voulais aussi changer le "fourré" à "buissons" juste parce que "fourré" pourrait donne des noms..... intéressants.... dans le jeu.

**Comment by b606** [comment]
J'ai eu Fourré Choco à un moment...

**Comment by Emjay89** [comment]
Délicieux ou obscène.... c'est difficile à dire! :-P
