### ISSUE TITLE
Traduction backstories "Cave tender"

### ISSUE THREAD

**Issue by Emjay89** [Ludeon/RimWorld-fr#216]
Je m'attaque à la traduction de backstories puisqu'il y en a tellement à faire! J'ai du mal à traduire le titre "Cave tender". Voici la description:
While the other were out hunting and foraging, PAWN_nameDef would stay at home to cook and take care of the young and sick.
Alors je propose un des titres suivants: 
-soignant des grottes
-ménager des grottes
-concierge des grottes

Lequel croyez-vous est le plus approprié?

**Comment by b606** [comment]
Aucune idée pour l'instant, j'ai vite regardé linguee.fr à "to tend" : soigner, garder, entretenir

**Comment by b606** [comment]
C'est métier qui se fait rare aujourd'hui :-)

**Comment by Emjay89** [comment]
C’est un peu plate comme backstory mdr! J’ai mis soignant en attendant qqch de meilleur.

**Comment by kiliak** [comment]
Nounou/Larbin/boy/homme à tout faire cavernicole?
Gardien de la grotte?

**Comment by b606** [comment]
Dans B18, c'était "Aide". Peut-être dans les synonymes "assistant/auxiliaire des cavernes" ou "concierge/gardien des cavernes", "ménager/homme au foyer"
