### ISSUE TITLE
Problème pour l'intégration des mots (masculin/féminin) venant des Strings/*.txt

### ISSUE THREAD

**Issue by b606** [Ludeon/RimWorld-fr#218]
Il faut un moyen pour déterminer (ou contourner) le genre masculin/féminin et le pluriel pour [Apparel],  [Vegetable], [Weapon], [Gore], [TreeType], [Community], [TerrainFeature], [PersonJob], [Enemy], [PersonFamily], [NaturalObject], [ConceptAny] etc (rajouter .txt pour trouver le fichier)

Par exemple, pour l'utilisation de Vegetables.txt on a dans RulePacks_Art_Descriptions.xml ou RulePacks_Global.xml : 
(genre fem/masc ?)
    `<li>subimagesingle->un(e) [Vegetable]</li>`
(forme au pluriel ? pour l'instant ou rajoute un (s) bêtement)
    `<li>subimageplural->[Quantity_adjphrase] [Vegetable]s</li>`
(pluriel et genre : amicaux/amicales)
    `<li>TalkTopicLight->des [PersonJob]s amicaux</li>`

Ça génère des "un(e)" "un/une" "du/de la/des" partout et des accords masc/fem/pluriel incorrects.
Si quelqu'un a une idée ?

NB: pour [Game], c'est assez facile, il suffit que cela s'accorde à
```
    <li>TalkTopicLight->de jouer au [Game]</li>
    <li>TalkTopicLight->de s'exercer au [Game]</li>
    <li>TalkTopicLight->d'apprendre le [Game]</li>
```
et on peut toujours mettre dans Game.txt au masculin "jeu de X".

**Comment by kiliak** [comment]
Je dis peut être connexe mais est'il possible d'avoir 2 fichiers séparés: 1 pour la version singulier et 1 pour la version pluriel. Du coup on peut mettre les determinant directement devant les noms dans les fichiers.

Exemple: au lieu  dans le fichier on met le chou au lieux de chou

Enfin je ne sais même pas comment faire ca

**Comment by kiliak** [comment]
Ou alors modifier les fichiers pour n'utiliser que des mots du même genre, là va falloir bosser ses synonymes

**Comment by b606** [comment]
Avec l'annonce de Ison [sur le forum](https://ludeon.com/forums/index.php?topic=43979.0#new) on doit pouvoir tout résoudre maintenant. Mais il y a du boulot...

Petit extrait, les nouveaux tags : 
List of available symbols for Pawns:
{0}: John, a cat, a dog (short name if possible, otherwise indefinite form of the pawn kind)
{0_nameFull}: John Doe, a cat, a dog (full name if possible, otherwise indefinite form of the pawn kind)
{0_nameFullDef}: John Doe, the cat, the dog (full name if possible, otherwise definite form of the pawn kind)
{0_label}: John, Constructor; cat; dog (label (name + title))
{0_labelShort}: John, cat, dog (short name if possible, otherwise kind label)
{0_definite}: John, the cat, the dog (short name if possible, otherwise definite form of the pawn kind)
{0_nameDef}: John, the cat, the dog (short name if possible, otherwise definite form of the pawn kind)
{0_indefinite}: John, a cat, a dog (short name if possible, otherwise indefinite form of the pawn kind)
{0_nameIndef}: John, a cat, a dog (short name if possible, otherwise indefinite form of the pawn kind)
{0_pronoun}: he/she
{0_possessive}: his/her
{0_objective}: him/her
{0_factionName}: Some Community (faction name)
{0_factionPawnSingular}: colonist (faction member label)
{0_factionPawnSingularDef}: the colonist (faction member label (definite))
{0_factionPawnSingularIndef}: a colonist (faction member label (indefinite))
{0_factionPawnPlural}: colonists (faction members label)
{0_kind}: human, cat, dog (kind label)
{0_kindDef}: the human, the cat, the dog (kind label (definite))
{0_kindIndef}: a human, a cat, a dog (kind label (indefinite))
{0_kindPlural}: humans, cats, dogs (kind label (plural))
{0_kindBase}: human, cat, dog, deer (instead of buck/doe) (base genderless kind label)
{0_kindBaseDef}: the human, the cat, the dog, the deer (base genderless kind label (definite))
{0_kindBaseIndef}: a human, a cat, a dog, a deer (base genderless kind label (indefinite))
{0_kindBasePlural}: humans, cats, dogs, deer (base genderless kind label (plural))
{0_lifeStage}: teenager, baby, adult (life stage label)
{0_lifeStageDef}: the teenager, the baby, the adult (life stage label (definite))
{0_lifeStageIndef}: a teenager, a baby, an adult (life stage label (indefinite))
{0_lifeStageAdjective}: teenage, baby, adult
{0_title}: constructor (pawn title)
{0_titleDef}: the constructor (pawn title (definite))
{0_titleIndef}: a constructor (pawn title (indefinite))
{0_gender}: male, female (pawn gender)
{0_gender ? A : B}: A if male or neuter, B if female
{0_gender ? A : B : C}: A if male, B if female, C if neuter
{0_humanlike ? A : B}: A if humanlike, B if not

**Comment by Adirelle** [comment]
J'ai commencé à faire ces intégrations (cf. https://github.com/Ludeon/RimWorld-fr/compare/master...Adirelle:master) mais je me pose des questions:
* Quelqu'un a pu faire des tests avec les listes de mots par genre ? (WordInfo/Gender/Male.txt et WordInfo/Gender/Female.txt) Je ne sais même pas d'où prendre les mots à lister : de Strings ? les labes de DefInjected ? les deux ? Dont-on coller les groupes de mots tels qu'ils apparaissent (c'est-à-dire un bête copié-collé) ou doit-on les passer au singulier et découper les groupes en plusieurs mots ?
* Dois-je utiliser `{0_gender ? é : ée}` ou `é{0_gender ?  : e}` ? Je ne sais pas si la 2ème version fonctionne.

**Comment by Adirelle** [comment]
> Pour plus de lisibilité, il me semble que c'est mieux de ne pas mettre un caractère isolé devant les {...}.. Par exemple pour un/une plutôt remplacer par {0_gender ? un : une}, le/la par {0_gender ? le : la}, etc.

Je note.

Pour l'instant, je bosse sur une seule branche mais j'essaierai de faire des PR propres quand j'aurai un résultat satisfaisant.

**Comment by b606** [comment]
Je reprends juste la liste et ferme cette issue.
