### ISSUE TITLE
probleme avec les backstories

### ISSUE THREAD

**Issue by kiliak** [Ludeon/RimWorld-fr#219]
salut,
j'ai un souci avec les trads dse backstories. je ne vois plus les textes traduits en FR, tout est en EN même ce qui est déja traduit.
comment c'est chez vous? j'ai fait une boulette?

**Comment by Emjay89** [comment]
Bizare....... je vais aller voir ça en arrivant chez moi.... j’ai rien fait de différent quand j’ai le dernier commit pour les backstories....

**Comment by b606** [comment]
En regardant le fichier dans le code ici, tout est en français jusqu'à ligne 1711...

**Comment by kiliak** [comment]
j'ai désinstallé et réinstallé mais pas de différence.

.je pense avoir fait une fausse manip aujourd’hui ...mais laquelle? là est la question .

**Comment by b606** [comment]
As-tu réussi à résoudre le problème ?
J'ai l'impression que tu as juste écrasé les fichiers RimWorld-fr avec la version French du jeu.

**Comment by kiliak** [comment]
Et bien non je vois pas du tout ce qui c'est passé. mes backstories restent en anglais même en ayant téléchargé le fichier issu du master.??????
Quand j'édite le fichier backstories de mon jeu j'ai bien la version partiellement traduit comme sur le master mais en jeu ce n'est pas traduit. 
Ca ne concerne que ce fichier le reste en en francais, ... j'vois pas là.
C'est comment chez vous?

**Comment by b606** [comment]
Il y avait une erreur XML dans les backstories. Revérifie avec mon dernier commit.

J'ai aussi relu jusqu'à la ligne 1964 (A-B-C-D + <EarthColonist48> et <Empath47>.
Je vais faire un gros PR pour qu'on puisse en discuter un peu.

**Comment by kiliak** [comment]
ok ça marche, je ne vois pas ce que tu as modifié mais c'est ok ingame pour moi....et je vois une quantité incroyable de fautes a corriger :)
