### ISSUE TITLE
erreur d'aiguillage d'un fichier

### ISSUE THREAD

**Issue by kiliak** [Ludeon/RimWorld-fr#223]
Bon le boulet a encore frappé:
J'ai créé un PR pour des backstories que j'ai faites avec un éditeur de texte mais je me rend compte que je ne l'ai pas envoyé dans le dossier backstories pour fusionner avec le précédant, mais que je l'ai envoyé dans la racine master... créant un nouveau fichier. 

je n'y ai fait que 3 trads et quelques modifs, donc si faut supprimer OK.

Mais si quelqu'un peut le déplacer ...promis je touche plus mon clavier :)

de toute façon je vais continuer directement sur le master via github, avec un éditeur de texte je trouve ça trop lourd au niveau des manips même si c'est plus agréable a voir.

**Comment by b606** [comment]
L'éditeur peut te donner plusieurs avantages. Ce que j'apprécie beaucoup c'est :
- permettre de trouver des erreurs XML facilement.
- peut compléter un mot s'il existe déjà (çà évite quelques fautes de frappes)
- rechercher multifichier et écran coupé en deux pour comparaison

Je ne sais pas comment est Visual Code. Fais juste une petite vérification dans github avant d'envoyer le fichier.
Ne t'inquiète pas, de tout façon, avec git, toute erreur est récupérable.

**Comment by b606** [comment]
Tu peux déplacer le fichier à la main directement en écrasant Backstories/Backstories.xml, et refaire un commit.

**Comment by kiliak** [comment]
LOL dit comme ça  ça ne semble pas compliqué...mais non
j'ai trouvé comment le déplacé mais impossible de remplacer avec le commit sous prétexte que les noms des fichiers sont identiques.
et comble du bonheur en m'acharnant "rebelote" j'ai créé un nouveau répertoire backstories avec mon fichier.
je jette l'éponge!!!!
si tu peux le déplacé ça m'arrangera voir même s'il le faut  le supprimer ( j'ai essayé ça aussi mais pas trouvé comment faire) ...........Pffffffffffffff!!!!!! :)

**Comment by b606** [comment]
C'est exactement aussi simple que çà;-)
- **tant que tu n'as pas poussé le fichier sur github, tu fais ce que tu veux sur ton PC, les autres ne verront rien**
- si tu as fais un commit sur ton ordinateur, c'est toujours chez toi mais git a mémorisé ce que tu as fais
- si tu as mis le fichier dans un mauvais répertoire, tu vas dans l'explorateur de fichiers et tu le déplaces au bon endroit, ensuite tu nettoies les répertoires et les fichiers en trop (ou de ton éditeur de texte, tu le réenregistres dans le bon répertoire, ensuite tu supprimes l'autre)
- tu peux écraser le fichier sans problème, git l'a en mémoire dans les commits précédents au cas où.
- ensuite tu vérifies que tout est OK et tu re-commit, git voit que le fichier a changé de place, il enregistre le nouveau commit
- et tu pousses sur github, tout le monde voit la modif.

Je te laisse faire la manip ? 
:smile: 

PS: Vérifies juste que tout est OK avant de pousser sur master. Il y a peut-être une option pour ne pas créer un PR à chaque fois. Ne merge pas le PR tant que ce n'est pas OK.
PS2 : il y a un "f" en trop dans le fichier ligne 1900 et quelque

**Comment by kiliak** [comment]
Tu vas rire mais non je comprends toujours pas....là j'ai l'impression que mes parents avaient le même nom avant de se marier 😨.
Je cherche à faire les manipulations directement sur Ludeon/rimWorld-fr pas sur mon PC....et j'y arrive pas 😂.
Sérieux si tu peux faire a ma place va y, j'vais finir pas coller mon clavier dans mon écran. 😉

**Comment by b606** [comment]
OK, je n'ai pas bien compris ce qui te bloquait. Vérifie si c'est OK

**Comment by kiliak** [comment]
c,'est ok, 
je ne sais pas non plus ce qui me bloquait, je ne comprend vraiment pas le fonctionnement de github, merci.

je clos
