### ISSUE TITLE
NeedBatteriesDesc : le texte anglais fait mention de "wind generator" mais pas le texte français

### ISSUE THREAD

**Issue by Desintegr** [Ludeon/RimWorld-fr#231]
Bonjour.

Dans le fichier Keyed/Alerts.xml, pour NeedBatteriesDesc, le texte anglais fait mention de "wind generator" alors que le texte français fait seulement mention de panneaux solaires.

Je pense qu'il faudrait modifier légèrement le texte français  :
> Vous avez des panneaux solaires ou des éoliennes, mais pas de batteries.
> Cela signifie que vous tomberez à court d'énergie à chaque fois que le soleil se couche ou que le vent se calme.\n\nConstruisez une batterie ou deux pour pouvoir maintenir l'électricité.

```
 <!-- EN: Need batteries -->
 <NeedBatteries>Batteries nécessaires</NeedBatteries>
 <!-- EN: You have a solar or wind generator, but no batteries. This means you'll lose power every time the sun goes down or the wind calms.\n\nBuild a battery or two to guarantee sustained power. -->
 <NeedBatteriesDesc>Vous avez seulement des panneaux solaires et pas de batteries. Cela signifie que vous tomberez à court d'énergie à chaque fois que le soleil se couche.\n\nConstruisez une batterie ou deux pour pouvoir passer la nuit.</NeedBatteriesDesc>
```

**Comment by NeverPire** [comment]
Ça me paraît une excellente modification.

**Comment by NeverPire** [comment]
Je n'avais pas remarqué le retour à la ligne. Sans savoir avec certitude quel effet cela aurait réellement eu sur l'affichage, j'ai préféré le supprimer.

**Comment by NeverPire** [comment]
Je pense que tu peux fermer l'issue si ce que j'ai fait te convient.

**Comment by Desintegr** [comment]
C'est nickel :) Merci !
