### ISSUE TITLE
Question about WordInfo/Gender files

### ISSUE THREAD

**Issue by Adirelle** [Ludeon/RimWorld-fr#235]
This is question is mostly aimed at Rimworld developers. (@TynanSylvester maybe ?)

For which strings does the translation engine look in `WordInfo/Gender/{Male,Female,Neutral}.txt` files ? 

To elaborate: there are words and groups of words in `Words/*/*.txt`, and several kind of tags in the xml files. Which ones are searched in the WordInfo files ? Are they transformed before the search ? How ?

I can easily extract these (groups of) words ; actually I have already tried, see https://github.com/Adirelle/RimWorld-fr/tree/wordinfo-genders. As sorting them is quite tedious, I would better be sure this is taken into account and if not, how to do it properly.

**Comment by isonil** [comment]
Currently the only words used by this system in RimWorld are:

PawnKindDef.label
FactionDef.pawnsPlural
FactionDef.pawnSingular
ThingDef.label
WorldObjectDef.label

Whether you need to put them in the gender files depends on whether your translations use X_gender tags anywhere (where X is either a Thing or WorldObject), or X_definite, X_indefinite, faction_pawnsPluralDef, faction_pawnsPluralIndef, faction_pawnSingularDef, or faction_pawnSingularIndef if they depend on the gender of the object in your language.

GrammarResolver doesn't support _gender tags so you don't have to put words from Words/*/*.txt there.

**Comment by Adirelle** [comment]
Thanks for these information.
