### ISSUE TITLE
Cohérence nom d'objet/recette/technologie

### ISSUE THREAD

**Issue by Adirelle** [Ludeon/RimWorld-fr#237]
Pour quelques objets, il y a une incohérence entre le nom de l'objet, l'intitulé qu'on voit sur les ateliers et la description (voire le label) de la technologie dans l'onglet de recherche.

Par exemple, on pouvait trouver fusil de sniper, fusil à lunette et fusil de précision à différents endroits. J'ai tous harmoniser pour n'avoir que "fusil de précision" : https://github.com/Adirelle/RimWorld-fr/commit/8eb86f73d2178e10ae458bbed500a9565be94211

J'en ai repérés quelques autres mais je voudrais vos avis:

## Armure énergétique
  * technologie : https://github.com/Ludeon/RimWorld-fr/blob/f63f8071bbae43c4b23a38ee763a6a41bb131410/DefInjected/ResearchProjectDef/ResearchProjects_4_MultiAnalyzer.xml#L45
  * recette: https://github.com/Ludeon/RimWorld-fr/blob/f63f8071bbae43c4b23a38ee763a6a41bb131410/DefInjected/RecipeDef/ImpliedDefs.xml#L133
  * objet : https://github.com/Ludeon/RimWorld-fr/blob/f63f8071bbae43c4b23a38ee763a6a41bb131410/DefInjected/ThingDef/Apparel_Various.xml#L55

Idem pour le casque énergétique.

Quand j'ai commencé à jouer, j'ai mis un moment à faire le lien entre les deux. Maintenant, je ne sais pas s'il vaut mieux choisir "armure énergétique", "de marine", "de space-marine", "de troupes d'élite", etc... (Il y a aussi les deux termes différents dans la version anglaise, mais ce n'est pas vraiment notre problème.)

## Tourelle improvisée
  * technologie: https://github.com/Ludeon/RimWorld-fr/blob/f63f8071bbae43c4b23a38ee763a6a41bb131410/DefInjected/ResearchProjectDef/ResearchProjects_2_Electricity.xml#L68
  * "objet": https://github.com/Ludeon/RimWorld-fr/blob/3cc3975b38fe554fa948cd5e263b850a01b3eac3/DefInjected/ThingDef/Buildings_Security.xml#L88

Le libellé de la techno ne va pas : "mitrailleuse" et "mitraillette" sont synonymes, et "automatique" s'applique aussi aux armes. Je propose "tourelles automatisées".
Quand à l'objet, on peut laisser tel quel ou choisir "mini-tourelle" ou encore "tourelle portative".

Des avis ?

**Comment by b606** [comment]
Ces incohérences sont dues aux changements au cours du développement du jeu (d'où aussi les incohérences en anglais). Beaucoup des changements ci-dessus viennent de la différences entre B19 et 1.0.

La différence entre Recherche et objets fabriqués vient du fait que la même recherche permet de fabriquer différents objets du même type (il y a au moins trois "tourelles" je crois, "tourelle improvisée" étant la défense de base).

On avait eu une discussion sur ces termes. Je regarde de mon côté mais il me semble que : 
 - Il faut reprendre la dernière modif dans l'historique des commits (je pense que @kiliak les avait faites). 
 - Pour les armures je ne me souviens plus, je crois qu'il faut se référer au texte anglais.
 - j'éviterai ~mitraillette~ et ~tourelle portative~ (ce n'est pas "portative", en tout cas pour l'instant).
 - Les ImpliedDef mettent en valeur ces incohérences en récupérant de tous les côtés ce qu'il faut. Donc il faut regarder le commentaire au dessus pour le reporter dans le tag correspondant.

A+

**Comment by b606** [comment]
- **"PoweredArmor"** : il faut garder "armure de marine" dans `<Apparel_PowerArmor.label>` (ThingDef/Apparel_various.xml) et mettre "casque de marine" dans `<Apparel_PowerArmorHelmet.label>` (ThingDef/Apparel_Headgear.xml) pour coller au mieux à l'anglais.
967b7af86dc92a69c63bb94fdfb91337a113f580 : le changement de l'anglais en "marine armor".
b5059a036ce0e0f3bc92b769b91ff85547a71ed9 : le commit FR juste après reflète ce changement en "armure de marines" après discussion. La modification dans RecipeDef/ImpliedDefs.xml et ResearchProjectDef devraient avoir suivi mais ont été oubliées.
Dans ResearchProjectDef/ResearchProjects_4_MultiAnalyzer.xml, je serai d'avis de coller aussi au texte anglais, quitte à rajouter une explication supplémentaire : 
```<PoweredArmor.description>Vous apprend la robotique neuromimétique et les technologies de tissage de plastacier qui vous permettent de fabriquer des armures et des casques énergétiques **comme les armures de marines**.</PoweredArmor.description>```

- **"MiniTurret"** : "tourelles automatisées" semble convenir, et "mini-tourelle" colle à l'anglais. Dans ResearchProjectDef/ResearchProjects_2_Electricity.xml, on pourrait avoir en description quelque chose comme : 
```<GunTurrets.description>Vous permet la construction de tourelles automatisées armées de mitrailleuses **ou de canon**.</GunTurrets.description>```

Pour "SniperRifle", c'est bien "fusil de précision" partout.

A+
