### ISSUE TITLE
French Language Worker

### ISSUE THREAD

**Issue by Adirelle** [Ludeon/RimWorld-fr#239]
Hello,

According [this post](https://ludeon.com/forums/index.php?topic=44000.msg445383#msg445383) on the forum, I created a gist with the abstract and the french language worker: https://gist.github.com/Adirelle/c9186e8f61776c9ea2b45a64811f14fe

Right now, this is just a copy of the code from the forum but I will update it quite soon to reflect the needed changes. It is easier to follow using a gist since the gist tracks the changes. Note that though I am developer, I never worker with C#, so my changes would be approximative at best.

I have a question for @isonil though: I known some developpers are not comfortable about using regular expressions because of their complexity and/or their performance. What is the stance on the subject for Rimworld (for `System.Text.RegularExpressions`) ? The functionalities that would ease fixing the Language Worker would be: alternatives, pattern capturing (to be used in replacements) and word boundary detection.

**Comment by Adirelle** [comment]
Je me demande si on ne devrait pas juste inclure le fichier dans le répertoire Notes, même s'il n'est pas utilisé automatiquement, pour garder une trace.

**Comment by b606** [comment]
J'y ai pensé aussi. Est-ce qu'ils ont répondu ?

**Comment by Adirelle** [comment]
Ben non, comme tu vois. :)

**Comment by isonil** [comment]
@Adirelle Regular expressions are indeed a bit slower but I think it's ok if it's going to make implementing LanguageWorker much easier. Russian LanguageWorker for example uses many regular expressions.

**Comment by kiliak** [comment]
On clos?

**Comment by b606** [comment]
On peut je pense.
