### ISSUE TITLE
Quelques correctifs à appliquer à la traduction

### ISSUE THREAD

**Issue by NovFR** [Ludeon/RimWorld-fr#245]
- Oubli d'une majuscule à "trop"

\IncidentDef\Incidents_Map_Threats.xml

  <DeepDrillInfestation.letterLabel>Trop profond : infestation</DeepDrillInfestation.letterLabel>

- Un "u" en trop

\InspirationDef\Inspirations.xml

  <Frenzy_Go.endMessage>{0} est parven{0_gender ? u : ue : u(e)} à se calmer. Sa frénésie de mouvement a cessé.</Frenzy_Go.endMessage>

- Harmonisation entre la recette (grandiose) et le produit (monumentale)

\RecipeDef\ImpliedDefs.xml

  <Make_SculptureGrand.label>faire une sculpture monumentale</Make_SculptureGrand.label>
  <Make_SculptureGrand.description>Faire une sculpture monumentale.</Make_SculptureGrand.description>
  
  <Make_SculptureGrand.jobString>Fabrique une sculpture monumentale.</Make_SculptureGrand.jobString>

- GranitE

\RecipeDef\Various_Stone.xml

  
  <Make_StoneBlocksGranite.label>tailler des blocs de granite</Make_StoneBlocksGranite.label>
  
  <Make_StoneBlocksGranite.description>Tailler des morceaux de granite en blocs utilisables.</Make_StoneBlocksGranite.description>
  
  <Make_StoneBlocksGranite.jobString>Taille des blocs de granite.</Make_StoneBlocksGranite.jobString>

- GranitE

\TerrainDef\ImpliedDefs.xml

  
  <Granite_Rough.label>granite brut</Granite_Rough.label>
  
  <Granite_Rough.description>Sol de granite brut.</Granite_Rough.description>
  
  
  <Granite_RoughHewn.label>granite grossièrement taillé</Granite_RoughHewn.label>
  
  <Granite_RoughHewn.description>Sol de granite grossièrement taillé.</Granite_RoughHewn.description>
  
  
  <Granite_Smooth.label>granite poli</Granite_Smooth.label>
  
  <Granite_Smooth.description>Sol de granite poli.</Granite_Smooth.description>

- GranitE

\TerrainDef\Terrain_Floors_StoneTile.xml

  
  <FlagstoneGranite.label>pavés en granite</FlagstoneGranite.label>
  
  <FlagstoneGranite.description>Pavés en granite. Pas super joli, mais c'est un bon revêtement pour les routes et les allées extérieures.</FlagstoneGranite.description>

  
  <TileGranite.label>carrelage en granite</TileGranite.label>
  
  <TileGranite.description>Carrelage en granite, pour donner un look de château. Joli, mais long à poser.</TileGranite.description>

- GranitE

\ThingDef\Various_Stone.xml

  
  <SmoothedGranite.label>granite lissé</SmoothedGranite.label>

- Erreurs concernant les étapes d'ébriété

\ThoughtDef\Alcohol_Beer.xml

  
  <Inebriated.stages.alcohol_warmth.label>Ébriété : réchauffé(e)</Inebriated.stages.alcohol_warmth.label>
  
  <Inebriated.stages.alcohol_warmth.description>Je me sens un peu plus détendu(e) après ce verre. Ça fait du bien.</Inebriated.stages.alcohol_warmth.description>
  
  <Inebriated.stages.quite_inebriated.label>Ébriété : pompette</Inebriated.stages.quite_inebriated.label>
  
  <Inebriated.stages.quite_inebriated.description>J'ai un peu la tête qui tourne ! C'est vraiment agréable.</Inebriated.stages.quite_inebriated.description>
  
  <Inebriated.stages.drunk.label>Ébriété : ivre</Inebriated.stages.drunk.label>
  
  <Inebriated.stages.drunk.description>Je me sens invincible, libre ! Je passe un super moment !</Inebriated.stages.drunk.description>
  
  <Inebriated.stages.hammered.label>Ébriété : ivre mort(e)</Inebriated.stages.hammered.label>
  
  <Inebriated.stages.hammered.description>Woua ! Il se passe quoi là ?</Inebriated.stages.hammered.description>

- Petite erreur dans la description

\TraitDef\Traits_Spectrum.xml

  
  <Beauty.degreeDatas.staggeringly_ugly.description>[PAWN_nameDef] est incroyablement lai{PAWN_gender ? d : de}. Son visage ressemble à un dessin d'enfant croisé avec un fœtus malformé à l'intérieur d'un bocal et une pièce d'art moderne. Lors des discussions, les gens doivent faire un effort de concentration pour ne pas être mal à l'aise à la vue de son visage.</Beauty.degreeDatas.staggeringly_ugly.description>

- Il s'agit d'entrées de menu donc ER

\Keyed\FloatMenu.xml

  
  <OrderManThing>Manipuler {1_labelShort}</OrderManThing>
  
  
  <MeleeAttack>Attaquer {1_label} au corps-à-corps</MeleeAttack>
  
  <MeleeAttackToDeath>Attaquer {1_label} au corps-à-corps jusqu'à ce que mort s'ensuive</MeleeAttackToDeath>

- Wd > Wj

\Keyed\Incidents.xml

  
  <ShortCircuitDischargedEnergy>{0} Wj d'énergie contenue dans les batteries ont été déchargés par une explosion électrique.</ShortCircuitDischargedEnergy>

- DuréE

\Keyed\Time.xml

  
  <Lasted>Durée</Lasted>

**Comment by b606** [comment]
Bonjour,
Merci pour les corrections !
J'ai tout mis dans master sauf \Keyed\Time.xml "Durée". En comparant avec "Débuté" çà parait ambigue et je n'ai pas pu vérifier où dans le jeu çà apparait. Est-ce que dans le jeu, c'est mieux "a débuté"/"a duré" ?

**Comment by NovFR** [comment]
Salut ^^

C'est utilisé lors des incidents de type éclipse ou vague de chaleur. C'est effectivement dans le sens "A duré" et "A débuté":

Débuté: {date du début}
Duré: {temps écoulé depuis le début}

Après, je ne sais pas si ces chaînes sont utilisées ailleurs.

**Comment by b606** [comment]
Bonjour !
Je crois que ces chaînes ne sont utilisées que là (à surveiller).
J'ai oublié de changer le tag `<Beauty.degreeDatas.staggeringly_ugly.description>`,  il y a peut-être une traduction un peu plus simple (?)

La version EN est 
> Others must exert conscious effort to look at [PAWN_objective] while conversing.

Actuellement FR est 
> Lors des discussions, les gens doivent faire un effort de concentration pour [PAWN_objective] regarder

La proposition est
> Lors des discussions, les gens doivent faire un effort de concentration pour ne pas être mal à l'aise à la vue de son visage.

**Comment by NovFR** [comment]
Ah, oui j'avais oublié que j'avais modifié cette partie. En fait, c'était surtout pour le
`laidi{PAWN_gender ? d : de}`
à changer en
`lai{PAWN_gender ? d : de}`
afin de donner laid et laide plutôt que laidid et laidide.

La seconde modification est davantage personnelle et pas vraiment nécessaire.

**Comment by b606** [comment]
Ah OK, bien vu ! 
C'est fait pour `lai{PAWN_gender ? d : de}`.

**Comment by NeverPire** [comment]
J'imagine que ça a été corrigé depuis le temps et vu la masse de conversations actives, je me permet de fermer celle-ci.
