### ISSUE TITLE
Traduction de techprint

### ISSUE THREAD

**Issue by b606** [Ludeon/RimWorld-fr#248]
J'ai pensé à
techprint : "fiche technique", "schéma technique" ou "schéma technologique"
mais toujours pas trouvé dans le jeu l'endroit où çà apparait (Recherche ?).

@kiliak  a signalé :
'pour "techprint/fiche technique " j'ai trouvé (et essayé de traduire) la description: Update Misc.xml ligne 103. Ça parle de quelque chose qui peut aller d'une feuille à une machine autonome. Je vous laisse phosphorer !!!"

**Comment by kiliak** [comment]
En jeu j'ai trouvé  référence à ça dans l'onglet recherche. Normalement quand une recherche est réalisable on valide Pau un gros bouton marron, si elle n'est pas valide (pas tout les prerequis) ce bouton est remplacé  par un message "techprint" avec un {0} et {1} dont je ne comprend pas l'origine

**Comment by b606** [comment]
Quand je clique sur une recherche non valide, j'ai juste "Bloqué, prérequis non satisfaits". Il doit y avoir d'autres conditions

**Comment by NeverPire** [comment]
Je le retrouve aussi dans Jobs_Misc :

**Comment by kiliak** [comment]
de même que pour le reste cela vient de l’extension Royaty, je prendrais l’extension, mais pas tout de suite, il va donc falloir attendre pour comprendre la mécanique et du coup la trad.

**Comment by b606** [comment]
C'est dans Royalty. Effectivement il est dans l'onglet Recherche. Il y a aussi des objets techprints. Si tout le monde est OK avec "schéma technique" on ferme cette issue. A+

**Comment by kiliak** [comment]
ok
