### ISSUE TITLE
Traduction de death acidifier

### ISSUE THREAD

**Issue by b606** [Ludeon/RimWorld-fr#249]
Lire la description.
Ne pas proposer "acidificateur de la mort"

**Comment by b606** [comment]
Dans DefInjected/PawnKindDef/PawnKinds_Mercenary.xml, plusieurs sont aussi "acidifier"

**Comment by kiliak** [comment]
Hier soir j'ai mi "dissolvant de la mort" à vous de boir

**Comment by b606** [comment]
Bone blague !

**Comment by b606** [comment]
"dissolvant de la mort" : je ne vais pas le boire ;-)

Pour les mercenaires : je suppose que vu le texte EN ces pawns n'ont pas besoin d'être différenciés. Morts, ils n'ont juste plus aucun matos. Est-ce qu'il y a d'autres intérêts dans le jeu ?

**Comment by NeverPire** [comment]
Dissolvant post-mortem ?

**Comment by NeverPire** [comment]
Je me permet d'utiliser cette traduction ici : 
DefInjected/RecipeDef/Hediffs_BodyParts_Bionic.xml

**Comment by kiliak** [comment]
Ta version est préférable,  elle fait plus serieuse

**Comment by NeverPire** [comment]
Je ne sais pas où d'autre il faut appliquer cette traduction, donc je vous laisse faire.

**Comment by b606** [comment]
On a deux traductions : "dispositif dissolvant post-mortem" ou "dissolvant post-mortem". Pour moi, ce n'est pas si grave. Si on est d'accord, on ferme ce topic.

DefInjected/RecipeDef/Hediffs_BodyParts_Bionic.xml
DefInjected/ThingDef/Hediffs_BodyParts_Bionic.xml
DefInjected/HediffDef/Hediffs_BodyParts_Bionic.xml
