### ISSUE TITLE
Toggle dans Keyed/Misc_Gameplay.xml

### ISSUE THREAD

**Issue by b606** [Ludeon/RimWorld-fr#251]
"Activer/Desactiver" est trop lourd à lire.
Les togglebuttons en général n'affiche que le texte résultat de l'activation.
Ex: Au lieu de "Activer l'affichage du truc", directement le verbe "Afficher le truc".
"Basculer" convient moins ; fait penser à un mouvement physique.

**Comment by kiliak** [comment]
Ça me va

**Comment by NeverPire** [comment]
Je pencherais plutôt pour ""commuter" le truc" qui a l'avantage de fonctionner à la fois pour activer et pour désactiver et enlève donc la "/".

**Comment by b606** [comment]
En fait, il y a deux catégories:
1. "Activer le X du truc" (ex Activer l'ajout auto Zone de Base)
2. "X_verbe le truc" (ex: Afficher)

J'ai mis çà hier, si vous pouvez tester comment çà rend dans le jeu.
