### ISSUE TITLE
Texte EN changé pour PoweredArmor.label ("marine armor")

### ISSUE THREAD

**Issue by b606** [Ludeon/RimWorld-fr#252]
A modifier dans DefInjected/ResearchProjectDef/ResearchProjects_4_MultiAnalyzer.xml

**Comment by kiliak** [comment]
Ce sont les nouvelles armures de reconnaissance?

**Comment by b606** [comment]
Non ce sont les anciennes. les tags juste au dessus de Recon

**Comment by NeverPire** [comment]
J'ai remplacé en armure de commando, ce qui est plus parlant. 
Les marines n'étant jamais que la version US/UK des commandos.

**Comment by b606** [comment]
Il faudrait synchroniser les Core/DefInjected/RecipeDef/ImpliedDefs.xml

**Comment by b606** [comment]
Fait !
