### ISSUE TITLE
Etabli de sculpture changé en EN "art bench"

### ISSUE THREAD

**Issue by b606** [Ludeon/RimWorld-fr#253]
DefInjected/ThingDef/Buildings_Production.xml
tag <TableSculpting.label>établi de sculpture</TableSculpting.label>
et vérifier un peu partout.

**Comment by NeverPire** [comment]
On le traduirait comment alors ?

En "repaire d'artiste" ?
Je n'ai pas encore trouvé mieux.

**Comment by b606** [comment]
Si on ne trouve pas, on laisse tel quel. Le texte EN a tendance à changer sans qu'on sache vraiment pourquoi.

**Comment by NeverPire** [comment]
Y a-t-il de nouvelles actions disponibles sur l'établi de sculpture différentes de la sculpture ?

**Comment by kiliak** [comment]
non toujours les 3 types de sculptures rien de neuf, mais ta proposition est bonne et reste assez générale pour d’éventuels rajouts. sinon  on peut aussi mettre "atelier d'artiste".

**Comment by NeverPire** [comment]
C'est vrai que c'est simple et fonctionnel.

**Comment by b606** [comment]
On peut aussi y fabriquer une harpe ou un clavecin.

**Comment by NeverPire** [comment]
Va pour "Atelier d'artiste" alors

**Comment by b606** [comment]
Çà me va aussi.

**Comment by kiliak** [comment]
ok
