### ISSUE TITLE
psychic silencer implant

### ISSUE THREAD

**Issue by b606** [Ludeon/RimWorld-fr#254]
Je ne vois pas en dev mod comment le générer.

**Comment by NeverPire** [comment]
Si il n'apparaît dans aucune catégorie en dev mode, c'est un bug, il devrait y être.

Si ça se vérifie, mieux vaut prévenir Tynan.

**Comment by b606** [comment]
J'ai tendane à croire que je suis devenu myope :-) A chaque issue, je ne vois rien dans rien. Ou alors c'est les 650 km de voyage hier.

**Comment by NeverPire** [comment]
Vu que j'en ai fait 900 avant-hier et que de mon côté ça va plus ou moins, va pour les lunettes.

**Comment by kiliak** [comment]
Vu qu'il a l'air de servir à camoufler l'utilisation des autres implants. On pourrait mettre:
"Implant de discrétion physique" ou "implant de camouflage psychique" ou plus fantaisiste "implant du silence psychique"

**Comment by NeverPire** [comment]
J'aime bien "Implant de discrétion psychique" , "Implant de furtivité psychique" ou même "Implant pour secret psychique"

**Comment by b606** [comment]
:+1:
