### ISSUE TITLE
Traduction de psycast

### ISSUE THREAD

**Issue by b606** [Ludeon/RimWorld-fr#255]
Essentiellement dans DefInjected/StatDef/Stats_Abilities.xml
Je n'ai pas encore rencontré ce terme dans le jeu. 

C'est juste une proposition intuitive : que pensez-vous de "Projection psychique" ?

**Comment by NeverPire** [comment]
En fonction de l'effet, ça pourrait aussi être télépathie, manipulation psychique ou influence psychique.

Avec ça, on devrait plus ou moins avoir fait le tour, plus qu'à choisir.

**Comment by kiliak** [comment]
Projection psychique

**Comment by kiliak** [comment]
sinon sur steam il y a ça dans la description de l'extension:

"Les titres donnent droit à un amplificateur psychique impérial. Ceux qui en détiennent un peuvent utiliser leur esprit pour manipuler et vaincre leurs ennemis. Les psycasters peuvent aveugler les ennemis ou les contrôler mentalement, bloquer les sensations de douleur ou conférer une concentration mortelle à un allié. Les psycasts avancés provoquent des vomissements de masse dans des foules d'ennemis, téléportent des objets ou des personnes, rendent les ennemis fous en masse ou rendent les alliés temporairement invisibles pour les attaques furtives.

Pour ceux qui souhaitent vivre en tant que rebelles contre l'Empire, il existe également d'autres moyens d'acquérir des amplificateurs psychiques."

ca peut aider?

**Comment by kiliak** [comment]
pouvoir psychique?

**Comment by b606** [comment]
Je ne sais pas si vous avez vu la video de Rhadamant qui passe en revue en détail la Royalty du point de vue d'un joueur
[https://www.youtube.com/watch?v=vfBZBOE4kaw](https://www.youtube.com/watch?v=vfBZBOE4kaw)

**Comment by NeverPire** [comment]
Pouvoir psychique ma paraît le plus général quand je vois la masse de capacités disponibles selon la vidéo.

**Comment by b606** [comment]
Si si, il y a CochlearImplant (prothèse auditive)

**Comment by NeverPire** [comment]
Ah, ça me rassure, je croyais qu'elles avaient été oubliées.

**Comment by b606** [comment]
Je lague dans la relecture à une centaine de commit plus loin (jusqu'au cou dans les QuestScript). Tu en es où ?

**Comment by NeverPire** [comment]
Je n'ai pas tout suivi faute de temps et dans tous les cas je me limite à ce qui a été traduit de manière manuelle, je n'ai pas les moyens de vérifier les modifications des "Keyed".


J'ai pour l'instant uniquement corrigé ce pour quoi j'ai eu des notifications, c'est à dire les traductions qui ont été commentées d'une manière ou d'une autre.

En ce qui concerne le reste, je commence à me demander.

**Comment by b606** [comment]
OK, mon dernier c'est GameConditions_Misc.xml (25 février). On avance et on verra après. J'essaie de finir les QuestScript de Core.

On basculera sur master quand je pourrai nettoyer un peu les warnings dans le fichier log de rimworld. Ca ralentit le démarrage.

**Comment by NeverPire** [comment]
J'ai donc ici tout vérifié pour le 28 et le 29 février.
