### ISSUE TITLE
ThoraxCanManipulate

### ISSUE THREAD

**Issue by NeverPire** [Ludeon/RimWorld-fr#256]
Je ne vois pas où cela apparaît, ni vraiment ce que cela veut dire donc si quelqu'un peut confirmer la traduction ça m'arrangerait :

https://github.com/Ludeon/RimWorld-fr/blob/unstable/DefInjected/BodyPartDef/BodyParts_Mechanoid.xml

  
  <MechanicalThoraxCanManipulate.label>thorax</MechanicalThoraxCanManipulate.label>

**Comment by b606** [comment]
J'ai trouvé dans RimWorld/Data/Core/Defs/Bodies/Bodies_Mechanoid.xml : le seul endroit, thorax des pikemans.

**Comment by NeverPire** [comment]
Je l'avais trouvé aussi, mais je ne suis absolument pas sûr de la traduction à apporter. Quand j'ai traduit le reste des parties des piquiers, je l'ai laissé en plan. Kiliak propose "Thorax".

**Comment by b606** [comment]
comme le texte EN est "thorax", on passe à autre chose. On laisse ouvert l'issue quelque temps, au cas où.

**Comment by kiliak** [comment]
J'avais proposé  thorax pour une traduction purement litherale sans savoir quoi en faire
