### ISSUE TITLE
PawnTrapSpringChance à vérifier

### ISSUE THREAD

**Issue by b606** [Ludeon/RimWorld-fr#257]
DefInjected/StatDef/Stats_Pawns_Combat.xml :
  <PawnTrapSpringChance.label> et <PawnTrapSpringChance.description>
  à vérifier.

J'ai plutôt compris "Chance de déclencher un piège" (par inadvertance) au lieu de "Chance de créer un piège que personne ne verra.", mais je n'arrive pas à trouver comment tester çà dans le jeu.

**Comment by NeverPire** [comment]
Tu fais créer plein de pièges dans le jeu en mode éditeur et tu vois si l'un d'eux est considéré comme non visible. Ça paraîtrait bizarre.

"Spring" peut se traduire par "faire sauter", "faire sortir" donc par pure logique je vote pour la traduction de b606.

**Comment by kiliak** [comment]
Effectivement

**Comment by b606** [comment]
J'ai trouvé. Ce texte apparait pour le caractère "agile" du personnage (EN: nimble)

Il faut : au début du jeu, générer un personnage agile (randomiser)
