### ISSUE TITLE
Attendre pour traduire : Recipes_Production.xml

### ISSUE THREAD

**Issue by NeverPire** [Ludeon/RimWorld-fr#258]
Mieux vaut attendre pour faire la traduction de ce fichier, car le texte anglais n'a aucun sens.
J'ai déjà été le déclarer sur le forum, j'attends leur correction pour démarrer la traduction.

Et oui, fondre des vêtements ne me paraît pas une bonne idée.

**Comment by b606** [comment]
Est-ce qu'ils t'ont répondu ? Je pense que d'un côté il y a "incinérer" (DestroyApparel), et de l'autre (SmeltApparel) "recycler" vu qu'on récupère des ressources. Je suppose que çà marche aussi bien pour les vêtements que les armures, et ils ont juste utilisé "Smelt" pour simplifier.

**Comment by NeverPire** [comment]
Je le pense aussi, mais la phrase d'explication avec les aimants n'a plus aucun sens.

Tynan m'a répondu qu'il voulait que je détaille, donc je l'ai fait et j'attend sa nouvelle réponse.

**Comment by NeverPire** [comment]
If it is not a problem for you that most of the apparels doesn't match with  the description, you can close the issue.
I will keep the original idea, maybe add an extra sentence to match fabric-only clothes recuperation in French.

Like in the title : " Dismantle apparel"
And in the description : "and heat to soften seams and recover fabric from clothes".

Donc je vais juste traduire en considérant ces ajouts dans les phrases anglaises.

**Comment by kiliak** [comment]
je sais j'arrive après la bataille, mais on pourrait mettre ligne 70:

Utilise l'association de la chaleur et des électro-aimants pour ramener les équipements a l’état de ressources réutilisables.

**Comment by b606** [comment]
Ils ont changé le EN en Use heat and strong electromagnets to break down metallic apparel like armor into useful resources.
Je crois que ce que tu as mis c'est bon

**Comment by NeverPire** [comment]
En fait ils ont changé ça suite à mon message sur le forum :D 

Je garde comme ça alors.
