### ISSUE TITLE
sortie de l'extension

### ISSUE THREAD

**Issue by kiliak** [Ludeon/RimWorld-fr#259]
juste pour prévenir une extension vient de sortir, faite donc attention dans les traductions.

le thème est la royauté, je trouvais que certains termes étaient étrange dans la traduction de la 1.1 ( trône, noble, royal notamment dans les vêtements) ou parlait de choses étranges ( navette) faites donc attention a en tenir compte dans les trads, nous sommes déjà entrain de traduire l’extension, il va donc falloir faire attention sur les interpretations.

**Comment by kiliak** [comment]
c'est sans doute de la que découle les questions sur les implants.

**Comment by NeverPire** [comment]
Aïe, j'ai un truc à corriger alors

**Comment by b606** [comment]
Nouveau TODO DefInjected/ExpansionDef
J'ai récupéré de l'outil de traduction du jeu, mais je n'ai pas mis tous les formatages de fichiers.
Seulement, les endroits où il y a quelques changements.
