### ISSUE TITLE
Mote ?

### ISSUE THREAD

**Issue by kiliak** [Ludeon/RimWorld-fr#261]
Juste par curiosité  quelqu'un peut me dire ce que sont tous ces Mote que l'on traduit par Mote? Il y en a dans plusieurs fichiers voir des fichiers ne contenant un ca.

**Comment by b606** [comment]
Je n'ai jamais compris ce que c'était. J'ai cru comprendre que ce n'était pas à traduire. Laisse tels quels ou en mettant Mote comme l'anglais.

**Comment by kiliak** [comment]
Ok

**Comment by NeverPire** [comment]
Je traduis par particule parce que je n'aime pas l'idée de laisser traîner un mot anglais.
De toute manière, à ce que je sache, ce mot n'apparaît pas en jeu.

**Comment by kiliak** [comment]
Je mettrais un message sur le forum , par pure curiosité

**Comment by b606** [comment]
Retrouvé ceci.
https://ludeon.com/forums/index.php?topic=47996.msg453568#new

**Comment by kiliak** [comment]
J'avais poster sur le forum officiel mais apparemment le sujet ne passionne pas les foules. Je ferme.
