### ISSUE TITLE
advanced helmet changé en "flak helmet"

### ISSUE THREAD

**Issue by b606** [Ludeon/RimWorld-fr#262]
avec l'arrivée de "recon helmet", ça se comprend.
A voir si on change de "casque avancé"

- [ ] DefInjected/ThingDef/Apparel_Headgear.xml
- [ ] DefInjected/RecipeDef/ImpliedDefs.xml

**Comment by kiliak** [comment]
au pire on peut le passé en "casque standard" ou casque "moderne". mais ça ne me choque pas de le laisser en "avancé"

**Comment by NeverPire** [comment]
"sophistiqué", au pire.

**Comment by b606** [comment]
Que pensez-vous de "renforcé" (comme flak pants et flak jacket) ?

**Comment by kiliak** [comment]
renforcé c'est bien aussi

**Comment by NeverPire** [comment]
C'est très bien renforcé

**Comment by b606** [comment]
J'ai mis "renforcé"
