### ISSUE TITLE
Information about Royalty extension translation

### ISSUE THREAD

**Issue by NeverPire** [Ludeon/RimWorld-fr#263]
From Tynan on the forum to all translators : 

Hi all, just a quick note on translating for Royalty.

You can do it in the same repo as the base language, just by making a folder for Core and one for Royalty.

The German translation has an example. See here: https://github.com/Ludeon/RimWorld-de

As always, thank you deeply to all translators.

**Comment by kiliak** [comment]
j'ai vu ce que les allemands ont fait , c'est carré, c'est germanique.
blague a part c'est bien foutu mais je en sais pas comment ils ont fait ca. Ca résoudrait bien mon problème de test in game car je n'arrive plus a correctement remplacer les fichiers du jeu par la version "unstable" depuis que j'ai l’extension.
si quelq'un y arrive bravo.

**Comment by b606** [comment]
C'est plus compliqué que çà. Il faut deux maintenant deux liens symboliques car la structure de répertoire n'est pas la même que celle du jeu directement.

Il faut que tu vois comment créer ces liens car tu serais bon pour copier à la mano deux fois: tu es sur windows ou mac ?

**Comment by b606** [comment]
PS : les germans n'ont utilisé que deux fois XXX_gender !!!

**Comment by kiliak** [comment]
Windows je verrait bien ce que ça donne, je connais pas l'allemand , je vais un peu mettre le nez dans leur trad ce WE, j'suis curieux.
Seulement 2 fois 👏👏👏
