### ISSUE TITLE
traduction de cluster

### ISSUE THREAD

**Issue by kiliak** [Ludeon/RimWorld-fr#264]
dans DefInjected/IncidentDef/Incidents_Map_Threats.xml :

  <MechCluster.label>groupe de mécanoïdes</MechCluster.label>
  
  <MechCluster.letterLabel>Groupe de mécanoïdes</MechCluster.letterLabel>
  
  <MechCluster.letterText>Un groupe de combats mécanoïdes a atterri à proximité. Le groupe sera initialement inactif, vous pouvez donc prendre le temps de décider comment l'attaquer.\n\nIl peut rester inactif jusqu'à ce qu'il soit dérangé, ou il peut avoir une minuterie ou bien des activateurs de proximité.\n\nLes mécanoïdes dormants ne sont pas inoffensifs . Ils peuvent rassembler de temps à autre des attaquants mécanoïdes, voire avoir un effet négatif plus large qui devra être traité à terme.</MechCluster.letterText>
   
j'avais traduit Cluster par "groupe" et proposé "grappe" je viens de penser a "amas".

qu'est-ce qui vous parle le plus?

**Comment by NeverPire** [comment]
Division, brigade, bataillon, troupe, escouade, section.

Je pensais plutôt à quelque chose dans ce goût-là.

**Comment by kiliak** [comment]
pourquoi pas mais ca fait tres militaire tout ca, , d'autres idées?

**Comment by b606** [comment]
Il faut voir le contexte. "groupe" est assez générique pour coller à toutes les sauces. "escouade" me plait bien aussi puisqu'il y a le sens qu'ils vont attaquer et que c'est un groupe assez petit. Les termes militaires se réfèrent à la taille du groupe.

**Comment by kiliak** [comment]
alors va pour escouade,
 l'aspect militaire me frenait un peu parce que pour moi ça donnerait une impression que les cluster sont des sortes de raiders /commando.
alors qu'ils fabriquent aussi des bases. je vais faire les changements on verra ce que ça donne.

**Comment by NeverPire** [comment]
Les soldats eux aussi construisent des bases. Personnellement, ça ne me choque pas.

**Comment by kiliak** [comment]
Donc pour rappel on a opté  pour "escouade", je clos.
