### ISSUE TITLE
traduction de stellarch

### ISSUE THREAD

**Issue by kiliak** [Ludeon/RimWorld-fr#266]
pensez vous neccaire de traduire "stellarch" et si oui par quoi?

definition :Le titre impérial de stellarch représente la domination d'un système stellaire tout entier. Dans l'Empire, étant donné que les temps de voyage interstellaires durent des années, les stellarch gouvernent leurs systèmes avec une grande indépendance. Chacun jure fidélité à l'empereur, mais comme l'empereur peut être à de nombreuses années-lumière, un stellarch peut passer des années ou des décennies sans interagir avec lui.

**Comment by NeverPire** [comment]
Régent/gouverneur stellaire/astral

Si on veut garder un jeu de mot : magnastral !

**Comment by kiliak** [comment]
Comme ça va revenir assez souvent je voudrait avoir plusieurs avis, mais oui j'avais aussi pensé à gouverneur stellaire.
 (voir même gouverneur impérial, mais là ça faisait très Warhammer 40k qui semble quand même bien inspirer l'extension).
Pour  le jeu de mot astraleader est bien mais reste du franglais et là on pourrait aussi bien rester sur stellarch.

**Comment by NeverPire** [comment]
En réalité le mot stellarque (avec un "que") a déjà été utilisé en français, notamment dans tout le cycle de SF "Perry Rhodan", mais personnellement je lui reproche de ne pas être directement compréhensible par un francophone.

**Comment by kiliak** [comment]
ok je mettrais gouverneur stellaire on verra plus tard s'il faut changer pour autre chose

**Comment by NeverPire** [comment]
Ou le stellarque, tant pis. Vu que ça existe déjà.

**Comment by b606** [comment]
J'aurai tendence à penser comme toi : "stellarque" sonne vraiment bizarre.

**Comment by NeverPire** [comment]
On risque d'utiliser ce mot à la pelle, il faut se décider pour uniformiser la traduction donc gouverneur stellaire

**Comment by b606** [comment]
Ça me va :+1:
