### ISSUE TITLE
Traduction de Royalty/Keyed/Letters.xml

### ISSUE THREAD

**Issue by zerah54** [Ludeon/RimWorld-fr#269]
Hello !

Après quelques PR concernant de bêtes typo histoire de me faire un peu la main, je me suis attaquée à la traduction de letters.xml (j'ai fait au hasard pour savoir quel fichier traduire ^^')

Il reste quelques TODO sur lesquels je n'ai pas osé me pencher car je n'étais vraiment, mais alors vraiment pas sûre de moi : (le principal problème étant que je ne suis pas encore hyper à l'aise avec les variables et leurs "déclinaisons" ^^' et comme ces phrases en sont bourrées c'est assez difficile à lire je trouve.

- EN: {PAWN_possessive} {TITLE} title was inherited by {HEIR_nameFull}, according to the succession laws of {FACTION_name}. It replaced {HEIR_possessive} {REPLACEDTITLE} title.
  _<LetterTitleInheritance_AsReplacement>TODO</LetterTitleInheritance_AsReplacement>_
  
- EN: {PAWN_possessive} {TITLE} title would have been inherited by {HEIR_nameFull} according to the succession laws of {FACTION_name}, but {HEIR_pronoun} already had a {HIGHERTITLE} title.
  _<LetterTitleInheritance_NoEffectHigherTitle>TODO</LetterTitleInheritance_NoEffectHigherTitle>_

-  EN: {PAWN_possessive} {TITLE} title was inherited by {HEIR_nameFull} according to the succession laws of {FACTION_name}.
  _<LetterTitleInheritance_WasInherited>TODO</LetterTitleInheritance_WasInherited>_

-  EN: {PAWN_possessive} {TITLE} title was not inherited by anyone, since {PAWN_pronoun} had no designated heir for this title.
  _<LetterTitleInheritance_NoHeirFound>TODO</LetterTitleInheritance_NoHeirFound>_

De plus, pour une phrase comme celle-ci par exemple : 
- EN: {PAWN_pronoun} demands a throneroom that meets these requirements:{1}

Je suis tentée de mettre "{PAWN_pronoun} réclame une salle du trône qui **satisfasse** ces exigences : {1}" mais je sais pas trop, j'ai l'impression que ça peut en gêner certains qui préfèreraient **satisfait** (même si le premier me semble plus correct).

Si vous avez des avis sur ces différentes questions / traductions, je suis preneuse, le fichier est presque intégralement traduit de mon côté, ces points là mis à part :) (et si j'en vois d'autres je viendrai les rajouter ici).

Merci d'avance !

**Comment by b606** [comment]
Je vais te pousser les modifs que j'ai. Il faudra les tester dans le jeu en déclenchant en debug mode les événements correspondants (Cela devrait être bon mais je n'en étais pas sûr.)

Cà te familiarisera aussi avec le truc j'espère.

**Comment by b606** [comment]
J'étais vraiment juste dessus (voir 4 derniers commits). Je passe à un autre QuestScript

**Comment by zerah54** [comment]
Ah oui en effet, pour le coup je viens de voir passer tes commits xD

Je testerai un peu du coup, je ne connais pas encore bien le debug mode de RimWorld mais j'ai un peu bidouillé ce week-end pour voir de quoi il s'agissait, je devrais m'en sortir :) en tout cas merci d'être toujours aussi réactif ^^

**Comment by b606** [comment]
Pour "satisfasse" je crois que c'est plus correct en effet. 
[https://forum.leconjugueur.lefigaro.fr/viewtopic.php?id=1239](https://forum.leconjugueur.lefigaro.fr/viewtopic.php?id=1239)

Il y a site "grammaire" complet sur lequel je tombe souvent, mais je ne l'ai pas en tête.

**Comment by NeverPire** [comment]
Satisfasse est la seule possibilité correcte si l'on veut garder cette structure de phrase. 
À la rigueur "qui puisse satisfaire".

**Comment by zerah54** [comment]
Ohh, je viens de regarder tes commits, en fait les tiens sont dans core, non ? ce que j'ai fait est sur le letters.xml de Royalty/Keyed

**Comment by b606** [comment]
Ils sont normalement sur le même système de langue. Donc astuces interchangeables

**Comment by zerah54** [comment]
@b606 oui oui, c'est juste que je pensais qu'on avait fait le travail en double ^^ mais en fait non du coup

@NeverPire oui, je trouve qu'avec "satisfait" c'est très moche en plus d'être faux de toute façon, donc même si certains emploient cette tournure je n'arrive pas à m'y résoudre ^^ J'ai posé la question plus par acquis de conscience pour valider ma supposition à propos de "satisfasse" que pour proposer "satisfait" :D
