### ISSUE TITLE
Question sur le classement des nouveaux mots en male ou femelle (Core/WordInfo/Gender/)

### ISSUE THREAD

**Issue by kiliak** [Ludeon/RimWorld-fr#276]
Je peux faire ça demain midi, mais j'ai des questions sur comment ça marche:
- les mots arrivent comment dans la liste " New words"? Tu l'as fait toi même où il y un programme. 
- dois t'on classer un mot des qu'on l'a traduit pour ne pas accumuler le travail?
-j'ai vu dans liste "UNE bûche": c'est une erreur?
- doit'on effacer les nouveaux mots des que transféré dans la bonne liste ? Ou y a t'il une sorte de nettoyage?
- on les rajoute à la suite des autres? Ou doit on les ranger par ordre alphabétique en créant des nouvelles lignes?

**Comment by b606** [comment]
- C'est un script (Notes/scripts/update-wordinfo.sh) qui extrait automatiquement les mots du jeu et met dans new_words.txt les nouveaux mots.
- Ce n'est pas nécessaire de classer le mot tout de suite.
- Tag <WoodLog.tools.log.label>une bûche dans Core/DefInjected/ThingDef/Items_Resource_Stuff.xml, je pense que c'est une erreur.
- L'ordre n'a pas d'importance, ils se rangeront par ordre alphabétique avec le script.
- new_word.txt sera régénéré à chaque fois, mais le vider manuellement pour indiquer qu'il n'y a rien à classifier.

**Comment by kiliak** [comment]
OK,  je vois ça tout à l'heure

**Comment by kiliak** [comment]
du coup je pourrais aller dessus que ce soir

**Comment by kiliak** [comment]
fait

**Comment by b606** [comment]
Super ! :+1:

**Comment by kiliak** [comment]
et j'ai rectifié pour UNE buche , également dans le fichier d'origine.
