### ISSUE TITLE
Reste à traduire pour RW1.1

### ISSUE THREAD

**Issue by b606** [Ludeon/RimWorld-fr#288]
Je reprends la liste ici car l'issue #246 est devenue trop longue.
~~**Une mise à jour a rajouté quelques TODO**~~

---
Progression :
- **Core** : 3 ~~ +10~~ TODO (au début 1798), ~~dont **Backstories** : 0 TODO~~
- **Royalty** : 5 TODO  (au début 1092) 
---
- [x] Core/Backstories/Backstories.xml (69 TODO)
- [x] Royalty/DefInjected/QuestScriptDef/Scripts_ItemPodThreat.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_Intro_Wimp.xml
- [x] Royalty/DefInjected/QuestScriptDef/Scripts_RewardRaid.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_Hospitality_Root_Joiners.xml
- [x] Royalty/DefInjected/QuestScriptDef/Scripts_RewardMechpods.xml
- [x] Royalty/DefInjected/QuestScriptDef/Scripts_JoinerThreat.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_EndGame_RoyalAscent.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_Hospitality_Root_Prisoners.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_Intro_Deserter.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_PawnLend.xml
- [x] Royalty/DefInjected/QuestScriptDef/Scripts_Utility_Helpers.xml
- [x] Royalty/DefInjected/TaleDef/Tales_Job.xml

Mise à jour (16/03/2020)
- [x] Core/DefInjected/RecipeDef/Recipes_Food.xml
- [x] Core/Keyed/Dialogs_Various.xml
- [x] Core/Keyed/Misc_Gameplay.xml
- [x] Royalty/DefInjected/FactionDef/Faction_Empire.xml

**Comment by b606** [comment]
Quelques tags disponibles dans les Quests, vu en activant le log Grammar Résolution . Çà change un peu en fonction des quêtes mais globalement, on a :

```
  asker_nameFull-><color=#D09B61FF>Pulcheria Tornikos</color>
  asker_label-><color=#D09B61FF>Tornikos</color>
  asker_definite-><color=#D09B61FF>Tornikos</color>
  asker_nameDef-><color=#D09B61FF>Tornikos</color>
  asker_indefinite-><color=#D09B61FF>Tornikos</color>
  asker_nameIndef-><color=#D09B61FF>Tornikos</color>
  asker_pronoun->elle
  asker_possessive->sa
  asker_objective->elle
  asker_factionName-><color=#00BFFFFF>The Exodus Dominion</color>
  asker_kind->gouverneur stellaire
  asker_title->recon sniper
  asker_titleIndef->un recon sniper
  asker_titleDef->le recon sniper
  asker_royalTitle0->gouverneur stellaire
  asker_royalTitle0Indef->un gouverneur stellaire
  asker_royalTitle0Def->le gouverneur stellaire
  asker_royalTitleFaction0-><color=#00BFFFFF>The Exodus Dominion</color>
  asker_royalTitleInCurrentFaction->gouverneur stellaire
  asker_royalTitleInCurrentFactionIndef->un gouverneur stellaire
  asker_royalTitleInCurrentFactionDef->le gouverneur stellaire
  asker_bestRoyalTitle->gouverneur stellaire
  asker_bestRoyalTitleIndef->un gouverneur stellaire
  asker_bestRoyalTitleDef->le gouverneur stellaire
  asker_bestRoyalTitleFaction->The Exodus Dominion
  asker_age->24
  asker_chronologicalAge->647
  asker_relationInfo->
  asker_faction_name-><color=#00BFFFFF>The Exodus Dominion</color>
  asker_faction_pawnsPlural->impériaux
  asker_faction_pawnsPluralDef->le impériaux
  asker_faction_pawnsPluralIndef->un impériaux
  asker_faction_leaderTitle->haut gouverneur stellaire
  asker_faction_royalFavorLabel->faveur royale

```
Note: les bugs à asker_faction_pawnsPluralDef et asker_faction_pawnsPluralIndef, certains déterminants et élisions (de le->du conseiller; de les->des archers...)

**Comment by kiliak** [comment]
pour Royalty/DefInjected/TaleDef/Tales_Job.xml je ne vois pas ce qui est a faire, pas de TODO

**Comment by NeverPire** [comment]
On voit la fin.

**Comment by b606** [comment]
Royalty a augmenté de un TODO. Qui a fait le coup ?

**Comment by kiliak** [comment]
non coupable...enfin j'y mettrais pas mes bijoux de famille a couper.
une idée d'ùu il a été rajouté?

**Comment by b606** [comment]
C'était une blague :smile:

**Comment by kiliak** [comment]
Faut pas jouer avec ca, j'en aurais été  capable 😂😂😂

**Comment by NeverPire** [comment]
Je pourrai faire une relecture complète à partir de ce week-end. Le covid-19 a neutralisé tout mon planning pour 8 semaines, donc j'ai tout mon temps.

**Comment by b606** [comment]
:+1: 
Que se passe-t-il en Belgique ?

**Comment by kiliak** [comment]
la même chose qu'en France fermeture des écoles non?

**Comment by NeverPire** [comment]
Ça a été annoncé il y a une heure, à partir de vendredi minuit, fermeture de toutes les institutions scolaires, de tout l'euréka (restaurants, etc ...), interdiction de tout rassemblement non nécessaire, fermeture de tous les magasins non alimentaires ou pharmaceutiques le week-end et étalement des horaires de sortie et d'entrée dans les entreprises pour éviter les concentrations de personnes.

**Comment by b606** [comment]
Mince, je n'ai pas regardé les infos.

**Comment by kiliak** [comment]
un peu plus radical qu'en France, moi il faut que je trouve ou mettre les petits a partir de lundi, apparemment les grands parents sont a mettre sous une cloche de verre.

**Comment by NeverPire** [comment]
Pour le coup, les autorités belges ont réfléchi, toutes les personnes devant recourir au service des grands-parents ou actifs dans les soins de santé peuvent amener leurs enfants aux écoles ou des "garderies" seront organisées.

**Comment by b606** [comment]
J'étais en train de jubiler quand les nouveaux TODO sont arrivés (une petite dizaine pas trop compliqués)

**Comment by ivarox** [comment]
Bonjour à tous et pour débuter je vous prie d'accepter mes excuses pour mon intrusion ici.

J'aurais aimé savoir où en est la traduction de Royalty ? Ou alors où regarder pour en être informé ?

En effet, il y a très peu d'informations qui circule à ce sujet et malgré mes recherches je ne trouve rien de concluant.

Ce n'est donc pas dutout un message pour vous stresser ou autre.... Rien de plus qu'une demande d'information ou de redirection .

D'avance un GRAND merci et merci également pour votre travail.

Bruno

**Comment by b606** [comment]
Vous avez le nombre de TODO qui restent au début de ce thread. Royalty et les Backstories viennent d'être faits dans la branche unstable. Il nous faut tester cette branche **unstable** pour ne pas générer des bugs dans le jeu. Si vous êtes intéressé pour les tests, téléchargez-la, ou voyez ici https://github.com/Ludeon/RimWorld-fr/wiki/R%C3%A9cup%C3%A9rer-les-nouveaux-fichiers-%C3%A0-traduire#configurer-les-fichiers-pour-github-et-rimworld-en-m%C3%AAme-temps- comment l'utiliser dans le jeu.

**Comment by ivarox** [comment]
Super merci beaucoup pour ces informations.

**Comment by kiliak** [comment]
N'esites pas à remonter tous ce qui semble étrange dans la trad

**Comment by kiliak** [comment]
je vois toujours les TODO dans les rajout du 16/03, mais sont cochés dans le listing, quelqu'un est dessus?

**Comment by b606** [comment]
Je suis dessus

**Comment by b606** [comment]
Encore des nouveaux TODO viennent d'arriver

**Comment by b606** [comment]
On met sur master ce qu'on a ce soir ?

**Comment by b606** [comment]
On l'a fait ! :clinking_glasses: :clinking_glasses: :clinking_glasses: :clinking_glasses: :clinking_glasses: 
C'est mis sur master, les seuls TODO qui restent sont dans les commentaires.
:1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: :1st_place_medal: 
à tout le monde

PS: Il y a aussi le choix de "funeste" et peut-être d'autres restés dans les discussions.

**Comment by kiliak** [comment]
Cool, 🍻🍻🍻bon ils vont bien changer quelques choses encore. 
Aucune idée s'y prendre mais il faudrait peut être créer une discutions  avec un listing de tous les points restant à voir/debattre
-pour moi c'est funeste

**Comment by b606** [comment]
- problème masc./fem. "bébé(M) étagne(F)" mal classé -> "cabri" (M) pour les petits et "éterlou (M)" "éterle (F)" pour les jeunes.?

**Comment by b606** [comment]
J'ai mis funeste et cabri, pour que çà ne traîne pas inutilement. Pour moi on peut clore cette issue

**Comment by kiliak** [comment]
Ok
