### ISSUE TITLE
All XXX_titleIndef and XXX_titleDef from backstories <titleFemale> are incorrect

### ISSUE THREAD

**Issue by b606** [Ludeon/RimWorld-fr#289]
The example of gramar log below shows that helpers0_titleDef and helpers0_titleIndef are set to incorrect values. In this case `helpers0` is clearly a female character, her title is from backstory `<PiousSoldier67>` with `<titleFemale>soldate pieuse</titleFemale>` or `<titleShortFenale>`
(only occurences in the langauge data).

- helpers0_titleDef should read "la soldate pieuse"
- helpers0_titleIndef should read "une soldate pieuse"

```
  helpers_count->3
  helpers0_nameFull-><color=#D09B61FF>Keegan Hyland</color>
  helpers0_label-><color=#D09B61FF>Hyland</color>
  helpers0_definite-><color=#D09B61FF>Hyland</color>
  helpers0_nameDef-><color=#D09B61FF>Hyland</color>
  helpers0_indefinite-><color=#D09B61FF>Hyland</color>
  helpers0_nameIndef-><color=#D09B61FF>Hyland</color>
  helpers0_pronoun->elle
  helpers0_possessive->sa
  helpers0_objective->elle
  helpers0_kind->janissaire
  helpers0_title->soldate pieuse
  helpers0_titleIndef->un soldate pieuse
  helpers0_titleDef->le soldate pieuse

```

**Comment by kiliak** [comment]
question un peu bête mais c'est quoi toutes ces issues avec le label bug , il faut faire quoi exactement? :)

**Comment by b606** [comment]
Trouver la solution :smile: 
Ici, pourquoi c'est marqué "un soldate pieuse" au lieu de "une soldate pieuse".

**Comment by kiliak** [comment]
ok bravo je ne comprend pas ce que tu as fait et ce que ca donne mais bravo 👍 .... sérieux je suis en galère avec l'utilisation des tags.

**Comment by b606** [comment]
This is an issue for the xxx_titleIndef and xxx_titleDef of any `<titleFemale>` from the backstories. In the examples below, one should read "xxx_titleIndef->**une** ..." and "xxx_titleDef->**la** ..." (the elision "l'artificière" is OK)

It looks like the LanguageWorker does not receive the correct gender information.
Storing all `<titleFemale>` and `<titleShortFemale>` in WordInfo/Gender/Female.txt will not solve the problem for unisex titles such as the "commissaire politique" or "gosse de riche" below.

```
  asker_pronoun->elle
  asker_possessive->sa
  asker_objective->elle
  asker_factionName-><color=#00BFFFFF>L'Empire De Kocas</color>
  asker_kind->soldate
  asker_title->commissaire politique
  asker_titleIndef->un commissaire politique
  asker_titleDef->le commissaire politique

  asker_pronoun->elle
  asker_possessive->sa
  asker_objective->elle
  asker_factionName-><color=#00BFFFFF>L'Empire De Kocas</color>
  asker_kind->soldate
  asker_title->gosse de riche
  asker_titleIndef->un gosse de riche
  asker_titleDef->le gosse de riche

  asker_pronoun->elle
  asker_possessive->sa
  asker_objective->elle
  asker_factionName-><color=#00BFFFFF>L'Empire De Kocas</color>
  asker_kind->soldate
  asker_title->artificière
  asker_titleIndef->un artificière
  asker_titleDef->l'artificière

  worker_pronoun->elle
  worker_possessive->sa
  worker_objective->elle
  worker_factionName-><color=#00BCD8FF>Nouveaux arrivants</color>
  worker_kind->colon
  worker_title->collectionneuse de machines
  worker_titleIndef->un collectionneuse de machines
  worker_titleDef->le collectionneuse de machines
```

**Comment by b606** [comment]
also reported on the forum https://ludeon.com/forums/index.php?topic=51212.0

**Comment by b606** [comment]
Also in Tales texts generation

```
  PAWN_pronoun->elle
  PAWN_possessive->sa
  PAWN_objective->elle
  PAWN_factionName-><color=#00BCD8FF>Nouveaux arrivants</color>
  PAWN_kind->colon
  PAWN_title->ingénieure en chef
  PAWN_titleIndef->un ingénieure en chef
  PAWN_titleDef->l'ingénieure en chef

```

**Comment by b606** [comment]
Noted fixed, thank you !
https://ludeon.com/forums/index.php?topic=51212.msg474742#msg474742
