### ISSUE TITLE
Bug in French Translation reported by Tynan

### ISSUE THREAD

**Issue by NeverPire** [Ludeon/RimWorld-fr#291]
https://ludeon.com/forums/index.php?topic=50993.0
https://ludeon.com/forums/index.php?topic=2977.300

This needs to be fixed ASAP because it is on the master.

**Comment by b606** [comment]
Already replied.

**Comment by b606** [comment]
J'ai généré un par un en dev mode une dizaine de chaque quest. À part ce que j'ai déjà signalé sur le forum RAS. J'attend juste ce qu'ils nous dise sur ces poignées de unresolvable. 

Je ne sais pas chez vous mais je pense que c'est mieux un merge sans squash : ma branche master s'affiche à mille ligne en dessous de unstable et c'est galère de passer de l'un à l'autre.

**Comment by NeverPire** [comment]
Je passe par le navigateur internet donc pour moi ça ne change rien si ce n'est que sans le squash, pour parcourir l'historique, je dois passer des pages entières.

**Comment by b606** [comment]
Pas de souci, j'ai animal-epicene en local. Pas besoin de l'avoir sur github. Il y a une solution à çà mais il faut programmer le LanguageWorker mais je n'ai pas le temps pour çà.

**Comment by b606** [comment]
Tu as sur le navigateur un petit bouton pour sélectionner la branche. Pour parcourir l'historique je ne sais pas. Tu n'as pas de possibilité avec GitHuB desktop ?

**Comment by NeverPire** [comment]
Je ne suis jamais parvenu à le faire fonctionner correctement et pourtant je m'y connais en programmation. Mais avec le vrai programme github, comment ceal se fait-il qu'il y ait des branches en plus qui apparaissent lorsqu'on  utilise un merge & squash.

**Comment by b606** [comment]
Si tu es en plein milieu d'un merge c'est normal pour des branches temporaires. Sinon, aucune idée. Je ne peux pas utiliser github desktop; Ils n'ont jamais été foutu de programmer çà pour linux. J'ai un peu fait le tour de mon côté sur ces outils en évitant les soft payants. le bon vieux gitk avec git-gui et un éditeur et kdiff3 me font vraiment l'affaire, étonnament.

**Comment by b606** [comment]
en fait, chaque soft fait son truc proprement de son côté  et rien de plus.
- gitk, interface vieillot mais efficace pour tout voir, et bouger les branches.
- voir les différences je lance kdiff3 à partir de gitk et çà saute aux yeux. Je ne sais pas ce que çà a de spécial dans ses couleurs pourries mais c'est mieux que le rose et vert de github. Appui sur un bouton et on modifie le texte.
- je veux me concentrer sur un fichier -> éditeur
- un commit, push, pull, merge etc, git-gui. Pour les rebase et gestion de conflits c'est plutôt ligne de commande chez moi.

**Comment by b606** [comment]
Je pense que cette issue est résolue. Je rappelle rapidement

- Vérifier que le XML est correct (tag ouvrant et fermant)
- Il faut bien faire attention aux contenus des tags :
- Ne pas changer un caractère ou un espace entre `<li>...->` ou entre `[...]` sauf si on sait que le [xxx] existe dans le jeu.
- S'il y a un point à la fin, il faut aussi en mettre en fraçais : ex. `Ils sonr arrivés|.|</li>`
- Respecter l'espace mis si l'anglais en a, c'est que le paragraphe de texte sera complété ailleurs : au début `<li>| |etc...` ou à la fin `et ainsi| |</li>`
- Vérifier systématyquement chaque changement avec le log Grammar Resolution activé : c'est le bouton avec le carré blanc en dev mode. Gros fichier assez "conséquent", le fichier de rimworld.log donnera alors la liste des tags autorisés, comme ceux que j'ai rélevé à #283 
- S'il y a une erreur, le log aura plein de texte en rouge.
