### ISSUE TITLE
inuformisation IEM/EMI/EMP ?

### ISSUE THREAD

**Issue by kiliak** [Ludeon/RimWorld-fr#298]
question un peu étrange mais en relisant certain fichier, j'ai vu qu'on avait parfois changer EMI par IEM, ok je comprend pourquoi, mais je ne sais pas si ça a été fait partout.

de plus je vois a de nombreux endroit l'emploi de EMP mais sur wiki https://fr.wikipedia.org/wiki/EMP cela semble être la même chose, faut 'il tout uniformiser et si oui comment tous les retrouver, il doit y en avoir un paquet.

**Comment by b606** [comment]
D'après ce que j'ai compris, c'est bien la même chose "impulsion électromagnétique". Si tout le monde est d'accord, on devrait mettre IEM partout. Le recherche de fichiers donne :
EMI
- [ ] Core/DefInjected/QuestScriptDef/Scripts_Utility_ThreatsCore.xml
- [ ] Royalty/DefInjected/SitePartDef/Buildings_ConditionCausers.xml
- [ ] Royalty/DefInjected/GameConditionDef/Buildings_ConditionCausers.xml
- [ ] Royalty/DefInjected/ThingDef/Buildings_ConditionCausers.xml
- [ ] Royalty/DefInjected/QuestScriptDef/Scripts_JoinerThreat.xml

EMP
- [ ] Core/DefInjected/RecipeDef/ImpliedDefs.xml
- [ ] Core/DefInjected/RulePackDef/RulePacks_Damage.xml
- [ ] Core/DefInjected/TipSetDef/Tips.xml
- [ ] Core/DefInjected/ThingDef/Items_Resource_Shell.xml
- [ ] Core/DefInjected/ThingDef/RangedIndustrialGrenades.xml
- [ ] Core/DefInjected/ThingDef/Buildings_Security.xml
- [ ] Core/DefInjected/ThingDef/ImpliedDefs.xml
- [ ] Core/DefInjected/ThingDef/Mote_Visual.xml
- [ ] Core/DefInjected/ThingDef/Apparel_Belts.xml
- [ ] Core/DefInjected/ThingDef/RangedIndustrial.xml
- [ ] Core/DefInjected/PawnKindDef/PawnKinds_Mercenary.xml
- [ ] Core/DefInjected/HediffDef/Hediffs_Global_Misc.xml
- [ ] Core/DefInjected/DamageDef/Damages_Stun.xml
- [ ] Core/Keyed/FloatMenu.xml
- [ ] Royalty/DefInjected/ThingDef/Buildings_Mech_ShieldGenerators.xml
- [ ] Royalty/DefInjected/ThingDef/MeleeUltratech.xml
- [ ] Royalty/DefInjected/ThingDef/MeleeBladelink.xml

**Comment by kiliak** [comment]
Ok et merci je vais attendre le retour des autres puis je ferais les modifications pour IEM

**Comment by kiliak** [comment]
Je pensais avoir le temps de finir les trad tranquillement avec la fermeture des écoles,  mais j'avais pas pensé que mon fils ferais ventouse sur le PC pour jouer à Fornite 😅, je ferais ça ce soir

**Comment by b606** [comment]
:smile:

**Comment by kiliak** [comment]
certaines références a EMI sont dans la version anglaise ou les tags,  je vérifie et les coche tout de même

**Comment by b606** [comment]
Je regarde les TODO restants

**Comment by kiliak** [comment]
c'est fait

**Comment by b606** [comment]
Je pense qu'on peut fermer cette issue
