### ISSUE TITLE
MAJ Tags à traduire

### ISSUE THREAD

**Issue by b606** [Ludeon/RimWorld-fr#300]
~~Une petite dizaine de TODO :~~
~~82 TODO~~

- [x] Core/DefInjected/RecipeDef/Hediffs_BodyParts_Prosthetic.xml
- [x] Core/DefInjected/ThingDef/Mote_Visual.xml
- [x] Core/Keyed/Misc_Gameplay.xml
- [x] Core/Keyed/Dialogs_Various.xml
- [x] Core/Keyed/Messages.xml
- [x] Core/Keyed/Menus_Main.xml
- [x] Royalty/DefInjected/RecipeDef/Hediffs_BodyParts_Bionic_Empire.xml
- [x] Royalty/DefInjected/RecipeDef/Hediffs_BodyParts_Archotech.xml
- [x] Royalty/DefInjected/RecipeDef/Hediffs_BodyParts_Prosthetic_Empire.xml
- [x] Royalty/DefInjected/RecipeDef/Hediffs_BodyParts_Archotech_EmpireRoyal.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_Hospitality_Worker.xml
- [x] Royalty/DefInjected/QuestScriptDef/Scripts_JoinerThreat.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_EndGame_RoyalAscent.xml
- [x] Royalty/Keyed/Designators.xml
- [x] Royalty/Keyed/Letters.xml

**Comment by b606** [comment]
Les deux premiers QuestScript n'arrêtent pas de bouger chaque minute.

**Comment by kiliak** [comment]
Pour Royalty/DefInjected/QuestScriptDef/Script_EndGame_RoyalAscent.xm c'est toujours le
 asker.NoLongerFactionLeader dont on ignore la traduction.

**Comment by b606** [comment]
On mettra ce qu'on a sur le master ce soir ? minuit comme dans les contes.
