### ISSUE TITLE
Trad erronée "Ce terrain est déjà plancher"

### ISSUE THREAD

**Issue by NeverPire** [Ludeon/RimWorld-fr#302]
Mauvaise traduction lorsque l'on essaie de placer un plancher en bois là où il y en a déjà.
"est déjà du ...." serait préférable.

![Rimworld sol](https://user-images.githubusercontent.com/14809903/77235221-4d192400-6bb4-11ea-87b2-8a3441703ba2.JPG)

**Comment by NeverPire** [comment]
Par contre je n'arrive pas à trouver où ça se trouve.

**Comment by b606** [comment]
Core/Keyed/Designators.xml:  `<TerrainIsAlready>Ce terrain est déjà {0}.</TerrainIsAlready>`

**Comment by b606** [comment]
Vérifie que çà marche pour tout type de sol : "carrelage" "pavé" "carreaux" "dalle" etc.

PS: est-ce qu'on continue avec la branche unstable ou tout sur master ?

**Comment by kiliak** [comment]
On est plus dans les correctifsalles que la trad, j'opéras bien pour un directe Master et faire un PR pour les grosses modifs

**Comment by NeverPire** [comment]
Pour les pluriels, ça ne marche pas, pour le reste si.

**Comment by b606** [comment]
"carreau de granit fin" est au singulier, il faut peut-être uniformiser.

si {0_definite} ou {0_indefinite} fonctionne (à tester un peu partout, des fois çà marche), je peux inclure les mots dans WordInfo/Gender pour avoir le bon déterminant.

**Comment by NeverPire** [comment]
Je vais regarder

**Comment by NeverPire** [comment]
Carreaux, pavés et dalle posent problème

**Comment by NeverPire** [comment]
Je vais passer au singulier tous les carreaux et transformer les "pavés de ..." en "sol pavé en ..." comme pour le "sol pavé en béton".
Pour la dalle, je pars sur "dallage en béton".

**Comment by NeverPire** [comment]
Maintenant tout fonctionne avec "ce terrain est déjà du ...".
