### ISSUE TITLE
label bizarre "Enflammé(e)"

### ISSUE THREAD

**Issue by b606** [Ludeon/RimWorld-fr#305]
Par rapport aux autres du même fichier (brûlure, engelures etc.)

https://github.com/Ludeon/RimWorld-fr/blob/9855d80b9bd89be48a45fa735f0bf67686ec7ab0/Core/DefInjected/DamageDef/Damages_Environmental.xml#L9-L12

**Comment by kiliak** [comment]
embrasement? je trouve que celui la est redondant avec burned

**Comment by b606** [comment]
Pourquoi pas. J'avais pensé à "mort par le feu". Je n'arrive pas à déterminer dans le jeu comment ce truc est enclenché.

**Comment by b606** [comment]
ou immolation ?

**Comment by kiliak** [comment]
pas mal immolation ça fait tres Jeanne d'Arc

**Comment by NeverPire** [comment]
immolation est le plus correct
