### ISSUE TITLE
Astuces au chargement accord de temps

### ISSUE THREAD

**Issue by NeverPire** [Ludeon/RimWorld-fr#306]
J'ai trouvé une erreur d'accord de temps dans une des astuces de chargement du jeu, par contre impossible pour moi de trouver le fichier lié.

C'était la phrase "Vous pouvez passer à côté de mécanoïdes dormants, ...."
La suite comprend deux erreurs de temps et comme c'était dans le chargement, impossible de faire une capture d’écran assez vite.

**Comment by kiliak** [comment]
c'est rectifié ( normalement :) ) c'était ici:
 RimWorld-fr/Royalty/DefInjected/TipSetDef/Tips.xml

**Comment by NeverPire** [comment]
Correct et bizarre, vu que je croyais être à jour :/
