### ISSUE TITLE
"Soldat arrived" non traduit

### ISSUE THREAD

**Issue by NeverPire** [Ludeon/RimWorld-fr#309]
Suite à l'acceptation d'une quête, le message "soldat arrived" et son contenu ne sont pas traduits.

C'est la quête ligne 111 dans QuestScriptDef/Scripts_ItemPodThreat.xml, mais ce n'est pas là que se trouve la phrase à traduire.

![RimWorld by Ludeon Studios 25_03_2020 16_55_51](https://user-images.githubusercontent.com/14809903/77559130-11d06b00-6ebc-11ea-96d0-f762211fb455.png)

Je viens de mettre à jour avec la toute dernière version de la traduction, mais cette quête était apparue juste avant, alors peut-être est-ce encore une fausse alerte.

**Comment by b606** [comment]
Pourrais-tu s'il te plait refaire un test avec le log Grammar Resolution activé, et envoyer le texte du log ?
1. enregistre ta partie sous un autre nom (test par ex.)
2. en dev mode, clique sur le bouton avec le carré blanc et coche Grammar (au milieu de la colonne de droite)
3. génère une quête du même type Scripts_ItemPodThreat que tu vas jouer jusqu'au bout (le bouton magique). Choisis la quête où ils envoient "quelqu'un pour vous aider".
4. envoie le fichier log dès que tu arrives sur cette même fenêtre

J'avais essayé avant et bizarrement je ne tombe jamais sur ce message qui indique que les aides sont arrivés.

**Comment by NeverPire** [comment]
Bon, je confirme, ce n'est toujours pas traduit.

**Comment by NeverPire** [comment]
La sauvegarde au passage : Save file : https://drive.google.com/open?id=15Ujn-0w_E-CkSGSqduv3TntmaVCWA-t1

**Comment by b606** [comment]
Je jette un coup d'oeil. As-tu pu avoir le log

**Comment by NeverPire** [comment]
Il est trop long, j'essaie de le découper

**Comment by NeverPire** [comment]
[Log.txt](https://github.com/Ludeon/RimWorld-fr/files/4385740/Log.txt)

**Comment by NeverPire** [comment]
Comme ça ça marche

**Comment by b606** [comment]
Tu es toujours sur RimWorld 1.1.2571 rev948 :smile: 
La dernière version stable est 1.1.2579, et même RimWorld 1.1.2584 rev1150 pour celle en cours de développement.

**Comment by NeverPire** [comment]
Je confirme, mais comme j'ai une version hors steam, les mises à jour ne sont pas automatiques et chaque mise à jour risque de créer des bugs avec un run commencé en 2563.

**Comment by b606** [comment]
Normalement, ils ont corrigé des bugs entre deux et çà marche un peu mieux. Le gros des risques était entre 1.0 et 1.1. Réenregistre le jeu dans un autre fichier pour le marquer à la version RW que tu utilises.

**Comment by b606** [comment]
Mais techniquement, je m'attends toujours au bug que tu as soulevé parce que je n'ai pas constaté de visu qu'on l'a résolu.

**Comment by b606** [comment]
On le saura quand la capture d'écran montre du français

**Comment by NeverPire** [comment]
Corrigé sous 2579

![RimWorld by Ludeon Studios 26_03_2020 10_38_59](https://user-images.githubusercontent.com/14809903/77632302-17769100-6f4e-11ea-9938-23083df19c98.png)

**Comment by NeverPire** [comment]
Je n'ai même pas dû le réenregister dans un autre fichier.

**Comment by b606** [comment]
Yahoooo ! tu m'enlèves une épine du pied :+1:
