### ISSUE TITLE
MaJ RimWorld 1.1.2584 rev992

### ISSUE THREAD

**Issue by b606** [Ludeon/RimWorld-fr#310]
Il y a des TODO et des textes en anglais changés

- [x] Core/DefInjected/QuestScriptDef/Script_TradeRequest.xml
- [x] Core/DefInjected/ThingDef/RangedMechanoid.xml
- [x] Core/Keyed/ITabs.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_BuildMonument_Root_Basic.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_BuildMonument_Worker.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_ChangeRoyalHeir.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_EndGame_RoyalAscent.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_Hospitality_Worker.xml
- [x] Royalty/DefInjected/QuestScriptDef/Scripts_Decree.xml
- [x] Royalty/DefInjected/QuestScriptDef/Scripts_JoinerThreat.xml
- [x] Royalty/DefInjected/ThingDef/Buildings_Mech_Turrets.xml
- [x] Royalty/DefInjected/ThoughtDef/Thoughts_Memory_Special.xml
- [x] Royalty/Keyed/Misc_Gameplay.xml

**Comment by kiliak** [comment]
quand il y en a plus il y a en encore :)

**Comment by b606** [comment]
On a eu deux jours de repos, çà va :smiley:
