### ISSUE TITLE
Quelques petites corrections

### ISSUE THREAD

**Issue by TheRealBix** [Ludeon/RimWorld-fr#314]
"Heavy SMG" devrait donner "pistolet-mitrailleur lourd" et non pas "mitrailleuse lourde"
Ce n'est pas une mitrailleuse mais une version plus lourde du "pistolet-mitrailleur".

"LMG" devrait se traduire par "mitrailleuse lourde" ou "mitrailleuse" tout court. C'est dans le jeu une version plus légère et accessible du minigun.

"Répéter jusqu'à en posséder X" est une tournure trop longue qui chevauche une partie de l'UI sur la gauche, la limite fixée est difficilement lisible.
"Répéter jusqu'à en avoir X" bien que moins soutenu améliorerait la lecture.
D'autres possibilités : "Répéter jusqu'à la limite", "Répéter jusqu'à X objets" ...

**Comment by b606** [comment]
Merci pour l'info !
Je modifie en conséquence.
