### ISSUE TITLE
[1.1.2632 rev719] Mise à jour vers les TKeys

### ISSUE THREAD

**Issue by b606** [Ludeon/RimWorld-fr#319]
Beaucoup de changements dans cette version. Il n'y a pas que les TKeys. Il y a
 - plusieurs TODOs, dont deux backstories supplémentaires,
 - des changements dans le texte en anglais (pas mal de textes, ex. go-juice, des questscripts),
 - et les changements de noms de tags (les TKeys), qui normalement ont été faits automatiquement dans les QuestScripts.

Liste des TODO (fait 157 / 157 à faire)
- [x] Core/DefInjected/RecipeDef/Hediffs_Local_Misc.xml
- [x] Core/DefInjected/GatheringDef/Gatherings.xml
- [x] Core/DefInjected/ThingDef/Mote_Water.xml
- [x] Core/DefInjected/ThingDef/Filth_Various.xml
- [x] Core/DefInjected/ThingDef/Items_Resource_Shell.xml
- [x] Core/DefInjected/ThingDef/Buildings_Security.xml
- [x] Core/DefInjected/ThingDef/Mote_MetaStatus.xml
- [x] Core/DefInjected/StatDef/Stats_Basics_Special.xml
- [x] Core/DefInjected/TraitDef/Traits_Singular.xml
- [x] Core/DefInjected/StatCategoryDef/StatCategories.xml
- [x] Core/DefInjected/MeditationFocusDef/MeditationFocuses.xml
- [x] Core/DefInjected/HediffDef/Hediffs_Local_Misc.xml
- [x] Core/Keyed/Misc.xml
- [x] Core/Keyed/Misc_Gameplay.xml
- [x] Core/Keyed/Letters.xml
- [x] Core/Keyed/MainTabs.xml
- [x] Core/Keyed/Dialogs_Various.xml
- [x] Core/Keyed/Dialog_StatsReports.xml
- [x] Core/Keyed/Messages.xml
- [x] Core/Keyed/WorkTags.xml
- [x] Core/Keyed/Menus_Main.xml
- [x] Core/Backstories/Backstories.xml
- [x] Notes/LanguageWorker_French.cs
- [x] Royalty/DefInjected/GatheringDef/Gatherings.xml
- [x] Royalty/DefInjected/TimeAssignmentDef/TimeAssignments.xml
- [x] Royalty/DefInjected/ThingDef/Ethereal_Various.xml
- [x] Royalty/DefInjected/ThingDef/Plants_Wild.xml
- [x] Royalty/DefInjected/ThingDef/Mote_Visual.xml
- [x] Royalty/DefInjected/ThingDef/Buildings_Misc.xml
- [x] Royalty/DefInjected/ThingDef/Apparel_Various.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_Hospitality_Utility.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_BuildMonument_Worker.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_PawnLend.xml
- [x] Royalty/DefInjected/AbilityDef/Abilities.xml
- [x] Royalty/DefInjected/IncidentDef/Incidents_Map_Special.xml
- [x] Royalty/Keyed/Misc_Gameplay.xml
- [x] Royalty/Keyed/Alerts.xml
- [x] Royalty/Keyed/MainTabs.xml
- [x] Royalty/Keyed/Dialogs_Various.xml
- [x] Royalty/Keyed/GameplayCommands.xml

Fichiers à reviser (textes EN changés, tags UNUSED, tags changés en TKeys)
- [x] Core/DefInjected/DifficultyDef/Difficulties.xml
- [x] Core/DefInjected/HediffDef/GoJuice.xml
- [x] Core/DefInjected/IncidentDef/Incidents_Caravan_All.xml
- [x] Core/DefInjected/InspirationDef/Inspirations.xml
- [x] Core/DefInjected/QuestScriptDef/Script_BanditCamp.xml
- [x] Core/DefInjected/QuestScriptDef/Script_DownedRefugee.xml
- [x] Core/DefInjected/QuestScriptDef/Script_ItemStash.xml
- [x] Core/DefInjected/QuestScriptDef/Script_LongRangeMineralScannerLump.xml
- [x] Core/DefInjected/QuestScriptDef/Script_PeaceTalks.xml
- [x] Core/DefInjected/QuestScriptDef/Script_TradeRequest.xml
- [x] Core/DefInjected/QuestScriptDef/Scripts_JoinerThreatCore.xml
- [x] Core/DefInjected/ResearchProjectDef/ResearchProjects_4_MultiAnalyzer.xml
- [x] Core/DefInjected/RulePackDef/RulePacks_Common.xml
- [x] Core/DefInjected/SitePartDef/Manhunters.xml
- [x] Core/DefInjected/ThingDef/GoJuice.xml
- [x] Core/DefInjected/ThoughtDef/Thoughts_Situation_Needs.xml
- [x] Core/DefInjected/TipSetDef/Tips.xml
- [x] Core/Keyed/Dialog_Trees.xml
- [x] Core/Keyed/Incidents.xml
- [x] Royalty/DefInjected/JobDef/Jobs_Misc.xml
- [x] Royalty/DefInjected/NeedDef/Needs.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_BuildMonument_Root_Basic.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_BuildMonument_Root_TimeProtect.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_ChangeRoyalHeir.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_EndGame_RoyalAscent.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_Hospitality_Root_Joiners.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_Hospitality_Worker.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_Intro_Deserter.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_Intro_Wimp.xml
- [x] Royalty/DefInjected/QuestScriptDef/Scripts_Decree.xml
- [x] Royalty/DefInjected/QuestScriptDef/Scripts_Decree_Utility.xml
- [x] Royalty/DefInjected/QuestScriptDef/Scripts_ItemPodThreat.xml
- [x] Royalty/DefInjected/QuestScriptDef/Scripts_JoinerThreat.xml
- [x] Royalty/DefInjected/QuestScriptDef/Scripts_RewardMechpods.xml
- [x] Royalty/DefInjected/QuestScriptDef/Scripts_RewardRaid.xml
- [x] Royalty/DefInjected/QuestScriptDef/Scripts_Utility_Helpers.xml
- [x] Royalty/DefInjected/RecipeDef/Hediffs_BodyParts_Archotech_EmpireRoyal.xml
- [x] Royalty/DefInjected/ResearchProjectDef/Apparel_Various.xml
- [x] Royalty/DefInjected/RulePackDef/Script_Hospitality_TextCommon.xml
- [x] Royalty/DefInjected/ThingDef/Apparel_Psychic.xml
- [x] Royalty/DefInjected/ThingDef/Buildings_Furniture.xml
- [x] Royalty/DefInjected/ThingDef/Hediffs_BodyParts_Archotech_EmpireRoyal.xml
- [x] Royalty/DefInjected/ThingDef/PsychicWeapons.xml
- [x] Royalty/DefInjected/ThoughtDef/Thoughts_Situation_Needs.xml
- [x] Royalty/DefInjected/TipSetDef/Tips.xml
- [x] Royalty/Keyed/Letters.xml

**Comment by b606** [comment]
**Traduction à valider :**

 - le matériau "eltex" -> "eltex"
 - fabriqué avec "eltex" -> "en eltex"
 - "psychic focusing", "psyfocus" -> deux traductions traînent dans les tags
    - "concentration psychique"
    - "focalisation psychique", "focalisation"
 - "psycaster" -> plusieurs traductions aussi
    - "unité psychique" (unité militaire) : "Tout vêtement d'unité psychique"
    - "utilisateurs de pouvoirs psychiques"
    - "criminal psycasters" -> "criminels et hors-la-loi dotés de capacités psychiques"
    - "tribal psycaster" -> cf les TODOs

**Changements dans le texte**
 - Réorganisation des textes dans les questscripts.
 - Sauf pour les TODO qui sont bien évidents, attention à bien vérifier, c'est très dur à suivre (i faut avoir sous les yeux les différences avant/après).
 - Beaucoup de changement autour des psycasters, psyfocus, méditations royales, lieu de méditation, etc.

**Comment by kiliak** [comment]
Salut, pour les Todo je verrais ça ce WE, là le déconfinement m'a mi sur les rotules... envore 2 jours ...pas de motivation pour aller autour de ça. 
-Pour le matériaux eltex j'aurais bien gardé le mot f'origine vu qu'il est totalement inventé. 
- pour X psycaster: X psychosensible ( c'est plus court que "X doté  de capacités phychiques)
Celui qui m'embêté le est "psyfocus" je ne vois rien de simple dans la langue de molière

**Comment by b606** [comment]
@kiliak : bien vu pour "scaria" -> rage, "blood rot" -> gangrène :+1: 
Deuxième vague de MaJ Ludeon :
    - "psychic amplifier" devient "psylink neuroformer"
    - Il n'y plus de "psychic silencer" ou de Bladelink
    - terme nouveau : psylink

**Comment by kiliak** [comment]
pour bladelink j'ai vu que tu avant remplacé par "arme intelligente" moi ça me va, mais sinon il y avait une autre option " arme consciente"

**Comment by kiliak** [comment]
"psylink" : lien psychique ou connexion psychique
psylink neuroformer alors là???????????

**Comment by b606** [comment]
Comme tu dis :smile: 
Mais où sont-ils allés chercher çà ?

**Comment by b606** [comment]
Bladelink : j'ai repris ce qu'il y avait déjà dans les descriptions

**Comment by kiliak** [comment]
alors pour moi celui là: Notes/LanguageWorker_French.cs c'est de l'araméen, je te le laisse :)

**Comment by kiliak** [comment]
j'ai coché ces 3 là:
Royalty/DefInjected/QuestScriptDef/Script_Hospitality_Utility.xml
Royalty/DefInjected/QuestScriptDef/Script_BuildMonument_Worker.xml
Royalty/DefInjected/QuestScriptDef/Script_PawnLend.xml
pas trouvé de TODO , ils semblent avoir été fait

**Comment by kiliak** [comment]
"psyfocus" peut aussi être un "point d'encrage psy/totem psy/ repère psy/point de focalisation phsychique". une sorte de support physique ( exemple arbre ou statuette) pour focaliser les capacités psy je vois pas comment le traduire correctement.

**Comment by b606** [comment]
Au final j'ai remis à jour un peu partout :
 * "psylink" -> "lien psychique"
 * "psylink neuroformer" -> "neuroformateur psychique"
Si quelqu'un a une meilleure traduction, on est toujours preneur.

**Comment by b606** [comment]
Tout est fait ici, je ferme. Next...
