### ISSUE TITLE
[1.1.2644 rev1035] Suite des mises à jour

### ISSUE THREAD

**Issue by b606** [Ludeon/RimWorld-fr#320]
Il y a (22 reste/130 TODOs) et quelques changements dans le texte EN.

- [x] Core/DefInjected/RecipeDef/Hediffs_Local_Misc.xml
- [x] Core/DefInjected/TipSetDef/Tips.xml
- [x] Core/DefInjected/ThoughtDef/Thoughts_Memory_Misc.xml
- [x] Core/DefInjected/StatDef/Stats_Abilities.xml
- [x] Core/DefInjected/StatCategoryDef/StatCategories.xml
- [x] Core/DefInjected/HediffDef/Hediffs_Local_Injuries.xml
- [x] Core/DefInjected/HediffDef/Hediffs_Local_Misc.xml
- [x] Core/Keyed/Misc_Gameplay.xml
- [x] Core/Keyed/FloatMenu.xml
- [x] Core/Keyed/MainTabs.xml
- [x] Core/Keyed/Dialogs_Various.xml
- [x] Core/Keyed/Dialog_StatsReports.xml
- [x] Core/Keyed/Menu_Options.xml
- [x] Core/Keyed/Menus_Main.xml
- [x] Royalty/DefInjected/TipSetDef/Tips.xml
- [x] Royalty/DefInjected/ThoughtDef/Thoughts_Situation_Special.xml
- [x] Royalty/DefInjected/ThingDef/Plants_Wild.xml
- [x] Royalty/DefInjected/ThingDef/Mote_Visual.xml
- [x] Royalty/DefInjected/ThingDef/Apparel_Various.xml
- [x] Royalty/DefInjected/JobDef/Jobs_Misc.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_Hospitality_Worker.xml
- [x] Royalty/DefInjected/StatDef/Stats_Pawns_General.xml
- [x] Royalty/DefInjected/NeedDef/Needs.xml
- [x] Royalty/DefInjected/IncidentDef/Incidents_Map_Special.xml
- [x] Royalty/DefInjected/HediffDef/Hediffs_Psycasts.xml
- [x] Royalty/Keyed/Misc_Gameplay.xml
- [x] Royalty/Keyed/Alerts.xml
- [x] Royalty/Keyed/Letters.xml
- [x] Royalty/Keyed/Dialogs_Various.xml
- [x] Royalty/Keyed/GameplayCommands.xml

**Comment by b606** [comment]
Super, il reste 22 TODOs :+1:

**Comment by kiliak** [comment]
voila c'est fait mais il ne restait que 10 TODO dans le dernier fichier il doit y en avoir 12 autres qui se baladent quelque part.
sinon je pense que les trad seront a ajuster en fonction du rendu en jeu, je n'ai rien testé. il y a des choses dont je ne suis pas satisfait.

**Comment by b606** [comment]
Les TODO sont faciles à retrouver par une recherche  multifichier.
- [ ] Core/DefInjected/MainButtonDef/MainButtons.xml
- [ ] Core/DefInjected/ThingDef/GoJuice.xml
- [ ] Core/DefInjected/ThingDef/WakeUp.xml
- [ ] Core/DefInjected/QuestScriptDef/Script_BanditCamp.xml
- [ ] Core/DefInjected/QuestScriptDef/Script_EndGame_ShipEscape.xml
- [ ] Core/DefInjected/HediffDef/Hediffs_Local_Injuries.xml
- [ ] Core/DefInjected/HediffDef/WakeUp.xml

Je rescane actuellement tout parce qu'il y a des textes EN changés que je n'avais pas eu le temps de traiter y compris dans les QuestScripts. 

Pas eu le temps de tester non plus. On fera çà après

**Comment by b606** [comment]
Je crois que c'est bon, les QuestScripts c'étaient chaud. 

**NOTE: toujours pas testé à cause du manque de temps. Remontez les problèmes si vous en rencotrez.**

On peut clore cette issue et passer à la version suivante :smiley:

**Comment by b606** [comment]
J'ai poussé quelques modifications supplémentaires. On est à jour avec 1.1.2647 rev896
