### ISSUE TITLE
Dame ou chevaleresse ?

### ISSUE THREAD

**Issue by b606** [Ludeon/RimWorld-fr#321]
Ne devrait-on pas traduire le féminin de chevalier par chevaleresse ?
https://fr.wiktionary.org/wiki/chevaleresse#fr
"(Histoire) (Noblesse) Celle qui avait reçu l’ordre de la chevalerie."
- "dame" me parait un peu décalée (carte de belote ou échecs : fait penser à reine, ou la femme de...)
- "chevalière" est possible mais ambigüe.

**Comment by kiliak** [comment]
j'y avais pensé a l"époque, quand je vois chevalière je pense tout de suite a Lady Oscar ( je sais je suis vieux).
 pour moi :chevalier/ dame ça fait moyen âge et chevalier/chevalière fait plus renaissance. après c'est juste une question de gout si tu préfère chevalière va y moi ça ne me choque pas.

**Comment by kiliak** [comment]
va pour chevaleresse... j'ai lu le wiki ca colle bien...mais j'avais jamais entendu le terme.

**Comment by b606** [comment]
Moi non plus, c'est ce qui m'a fait hésiter.

**Comment by NeverPire** [comment]
Ça correspond bien au féminin du titre.

**Comment by b606** [comment]
fait.
