### ISSUE TITLE
[1.1.2654 rev674] MaJ avec quelques TODOs et textes EN changés

### ISSUE THREAD

**Issue by b606** [Ludeon/RimWorld-fr#322]
Fichiers avec TODOs: 0 faits / 17 total

- [x] Core/DefInjected/TipSetDef/Tips.xml
- [x] Core/DefInjected/StatDef/Stats_Basics_Special.xml
- [x] Core/DefInjected/StatCategoryDef/StatCategories.xml
- [x] Notes/LanguageWorker_French.cs
- [x] Royalty/DefInjected/ConceptDef/Concepts_NotedOpportunistic.xml
- [x] Royalty/DefInjected/ThingDef/Plants_Wild.xml
- [x] Royalty/DefInjected/StatDef/Stats_Pawns_General.xml
- [x] Royalty/Keyed/Misc_Gameplay.xml
- [x] Royalty/Keyed/Dialogs_Various.xml
- [x] Royalty/Keyed/GameplayCommands.xml
- [x] Royalty/Keyed/Messages.xml

Textes EN changés, y compris les TODO
- [x] Core/DefInjected/DifficultyDef/Difficulties.xml
- [x] Core/DefInjected/HediffDef/Hediffs_Local_Misc.xml
- [x] Core/DefInjected/HediffDef/Hediffs_Local_TerrainAttacks.xml
- [x] Core/DefInjected/QuestScriptDef/Script_ItemStash.xml
- [x] Core/DefInjected/RecipeDef/Hediffs_Local_Misc.xml
- [x] Core/DefInjected/StatCategoryDef/StatCategories.xml
- [x] Core/DefInjected/StatDef/Stats_Basics_Special.xml
- [x] Core/DefInjected/TipSetDef/Tips.xml
- [x] Royalty/DefInjected/ConceptDef/Concepts_NotedOpportunistic.xml
- [x] Royalty/DefInjected/HediffDef/Hediffs_Local_Misc.xml
- [x] Royalty/DefInjected/PawnKindDef/PawnKinds_Empire.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_Hospitality_Root_Joiners.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_Hospitality_Worker.xml
- [x] Royalty/DefInjected/QuestScriptDef/Script_Intro_Deserter.xml
- [x] Royalty/DefInjected/RecipeDef/Hediffs_Local_Misc.xml
- [x] Royalty/DefInjected/RoyalTitleDef/RoyalTitles_Empire.xml
- [x] Royalty/DefInjected/StatDef/Stats_Pawns_General.xml
- [x] Royalty/DefInjected/ThingDef/Plants_Wild.xml
- [x] Royalty/Keyed/Dialogs_Various.xml
- [x] Royalty/Keyed/GameplayCommands.xml
- [x] Royalty/Keyed/Messages.xml
- [x] Royalty/Keyed/Misc_Gameplay.xml

**Comment by b606** [comment]
Dans Royalty/DefInjected/PawnKindDef/PawnKinds_Empire.xml, **esquire** (écuyer) est changé en **acolyte**, qui semble se référer à un ordre religieux (https://fr.wikipedia.org/wiki/Acolyte) ou par extension "serviteur" ? En français familier, "acolyte" est apparemment péjoratif.

**Comment by kiliak** [comment]
compagnon? après moi écuyer ca me va tres bien. c'est vrai acolyte ça fait un peu homme de main dans une secte ou bras droit du chef de gang :)

**Comment by b606** [comment]
Je crois que celui-à est fait. 
Reste une précision à apporter dans Core/Keyed/Dialogs_Various.xml pour les tags `<HighGain>, <HighFallRate>, <HighDuration>`

**Comment by b606** [comment]
J'ai mis à jour les tags concernant les effets des médicaments et drogues et l'addiction/dépendance dans le panneau d'information "**i**". Plusieurs textes concernés dans Core/Keyed/Dialog_StatsReports.xml et Core/Keyed/Dialogs_Various.xml.
Ils me semblent plus clairs maintenant mais n'hesitez pas à modifier si besoin.
