### ISSUE TITLE
Terme peu précis : "tout parqueté"

### ISSUE THREAD

**Issue by JGoutin** [Ludeon/RimWorld-fr#323]
Bonjour,

```xml
<!-- EN: all floored -->
<RoomRequirementAllFloored>tout parqueté</RoomRequirementAllFloored>
<!-- EN: all fine floored -->
<RoomRequirementAllFineFloored>tout finement parqueté</RoomRequirementAllFineFloored>
```

Le terme "parqueté" est imprécis dans le sens ou il est associé au parquet (généralement en bois) et fait donc penser qu'il faudrait mettre du "plancher en bois" alors qu'en pratique d'autres types de sols sont valides. De plus il n'y a pas de variante "raffinée" du plancher. Ceci est une erreur de compréhension vécue en jeu.

Un terme plus général serait plus approprié, mais il ne semble pas y avoir d'équivalent directe en français. Quelques idées:
- "entièrement pavé" / "entièrement finement pavé"
- "sol entièrement couvert" / "sol entièrement finement couvert"
- "sol entièrement décoré" / "sol entièrement finement décoré"
- "entièrement dallé" / "entièrement finement dallé" (Mais favorise le carrelage)

De plus en anglais, il est demandé d'avoir `fine floored` qui correspond directement au `fine carpet` et `fine tile` disponibles.
En français, pour représenter `fine`, il y a actuellement deux mots `raffiné`/`finement` (pour le carrelage et les plats) et `délicat` (pour les tapis). Utiliser un même mot (plutôt `raffiné`) dans toutes les situations éviterait toute confusion.

**Comment by kiliak** [comment]
Tu aurais une capture d'écran je ne vois pas où c'est.

**Comment by JGoutin** [comment]
C'est au niveau de l'aide pour les titres de noblesse .On peu l'obtenir en cliquant sur le titre d'un personnage noble dans sa page "Bio" puis ensuite sur les differents titres pour voir les exigences associés:

![Screenshot](https://user-images.githubusercontent.com/13535894/90381118-71e2cc00-e06c-11ea-8a45-23ccf9e9e62a.png)

**Comment by kiliak** [comment]
ok merci je vois mieux là.
j'aurais bien vu ''sol travaillé" /"sol finement travaillé" c'est général et pas trop lourd.

celui ci : "sol entièrement couvert" / "sol entièrement finement couvert" me plaisait bien dans tes propositions mais plus lourd a cause des entière**ment** fine**ment**

des avis sur le sujet?

**Comment by kiliak** [comment]
c'est fait : "sol couvert"/"sol finement couvert"
