### ISSUE TITLE
Suspendre/Reprendre: Inversion de sens

### ISSUE THREAD

**Issue by JGoutin** [Ludeon/RimWorld-fr#324]
```xml
<!-- EN: Suspended -->
<Suspended>Suspendre</Suspended>
<!-- EN: Not suspended -->
<NotSuspended>Reprendre</NotSuspended>
```

Dans le menu des taches de fabrication, le sens du bouton "Suspendre"/"Reprendre" ne correspond pas au statut de la tache:
* Si la tache est active le bouton affiche "Reprendre" (contre "Not suspended" en anglais).
* Si la tache est suspendue le bouton affiche "Suspendre" (contre  "Suspended" en anglais).

Les traductions devraient plutôt être "Suspendu" / "Non suspendu".

**Comment by kiliak** [comment]
Il y aurais aussi la possibilité  d'écrire : "Suspendu" / "en cours"

**Comment by kiliak** [comment]
fait: "Suspendu" / "en cours"
