### ISSUE TITLE
traduction pour la maj 1.2

### ISSUE THREAD

**Issue by kiliak** [Ludeon/RimWorld-fr#325]
Salut tout le monde , y aurait- il quelqu'un pour pousser les fichiers a traduire dans le Git? 
Je sais je sais ...j'ai toujours pas compris comme obtenir les TODO.

**Comment by boundir** [comment]
Salut @kiliak, je prépare ça.
Le générateur a remplacé plusieurs traductions par des TODO. Je corrige ce que je vois et je push dès que possible.
Git me signale également énormément de fichiers modifiés pour lesquels je ne vois aucune différence. Peut-être un encodage différent ¯\_(ツ)_/¯

J'essayerai également de faire compléter le guide pour extraire les nouvelles traductions.

**Comment by b606** [comment]
Bonjour
Je ne peux rien faire pour le moment. Pour les encodages, il y a un script dans Notes/scripts/normalize-eol.sh qui devrait tout mettre correctement.

A+

**Comment by boundir** [comment]
@b606 J'ai vu la partie Notes plus tard. Tous les scripts sont bon à être utiliser? Est-ce qu'il y a une doc ou une discussion quelque part?

**Comment by b606** [comment]
@boundir Les scripts sont normalement tous bons sauf si la structure des répertoires changent (ils doivent dater de 2-3 ans, j'ai dû modifier `scripts/update-wordinfo.sh` pour Royalty, Je crois que les allemands ont plus ou moins readaptés aussi scripts/update-wordinfo.sh pour leur besoin.)

Il n'y a pas de doc dessus dans le wiki ni dans les scripts eux-même. un petit guide serait le bienvenu.

Quelque part vers la version 1.1.2598, l'outil de traduction Ludeon reformate les fichiers de langage en encodage DOS au lieu de Unix comme auparavant. Il faudrait peut-être changer .gitattributes pour ne plus utiliser `normalize-eol.sh` à chaque mise à jour.
