### ISSUE TITLE
[1.2.2723] Liste des fichiers à traduire

### ISSUE THREAD

**Issue by boundir** [Ludeon/RimWorld-fr#326]
### Core

- [x] Core\Backstories\Backstories.xml:
- [x] Core\DefInjected\ApparelLayerDef\ApparelLayerDefs.xml:
- [x] Core\DefInjected\BodyPartDef\BodyParts_Humanoid.xml:
- [x] Core\DefInjected\BodyPartGroupDef\BodyPartGroups.xml:
- [x] Core\DefInjected\DifficultyDef\Difficulties.xml:
- [x] Core\DefInjected\ExpansionDef\ExpansionDefs.xml:
- [x] Core\DefInjected\HairDef\HairsGeneral.xml:
- [x] Core\DefInjected\HediffDef\Hediffs_Global_Misc.xml:
- [x] Core\DefInjected\JobDef\Jobs_Misc.xml:
- [x] Core\DefInjected\KeyBindingDef\KeyBindings.xml:
- [x] Core\DefInjected\MeditationFocusDef\MeditationFocuses.xml:
- [x] Core\DefInjected\PawnsArrivalModeDef\PawnsArrivalModes.xml:
- [x] Core\DefInjected\QuestScriptDef\Script_LongRangeMineralScannerLump.xml:
- [x] Core\DefInjected\RecipeDef\Recipes_Butchery.xml:
- [x] Core\DefInjected\ResearchProjectDef\ResearchProjects_2_Electricity.xml:
- [x] Core\DefInjected\ResearchProjectDef\ResearchProjects_3_Microelectronics.xml:
- [x] Core\DefInjected\RulePackDef\RulePacks_Event.xml:
- [x] Core\DefInjected\StatDef\Stats_Basics_General.xml:
- [x] Core\DefInjected\StatDef\Stats_Basics_Special.xml:
- [x] Core\DefInjected\ThingCategoryDef\ThingCategories.xml:
- [x] Core\DefInjected\ThingDef\Apparel_Packs.xml:
- [x] Core\DefInjected\ThingDef\Apparel_Utility.xml:
- [x] Core\DefInjected\ThingDef\Buildings_Structure.xml:
- [x] Core\DefInjected\ThingDef\Effecter_Damage.xml:
- [x] Core\DefInjected\ThingDef\Ethereal_OrbitalStrikes.xml:
- [x] Core\DefInjected\ThingDef\ImpliedDefs.xml:
- [x] Core\DefInjected\ThingDef\Items_Unfinished.xml:
- [x] Core\DefInjected\ThingDef\RangedIndustrialGrenades.xml:
- [x] Core\DefInjected\ThingDef\RangedSpecial.xml:
- [x] Core\Keyed\Alerts.xml:
- [x] Core\Keyed\Designators.xml:
- [x] Core\Keyed\Dialog_StatsReports.xml:
- [x] Core\Keyed\Dialogs_Various.xml:
- [x] Core\Keyed\Enums.xml:
- [x] Core\Keyed\FloatMenu.xml:
- [x] Core\Keyed\GameplayCommands.xml:
- [x] Core\Keyed\Letters.xml:
- [x] Core\Keyed\MainTabs.xml:
- [x] Core\Keyed\Menus_Main.xml:
- [x] Core\Keyed\Messages.xml:
- [x] Core\Keyed\Misc_Gameplay.xml:
- [x] Core\Keyed\Misc.xml:

### Royalty

- [x] Royalty\DefInjected\AbilityDef\Abilities.xml:
- [x] Royalty\DefInjected\FactionDef\Faction_Empire.xml:
- [x] Royalty\DefInjected\FactionDef\Factions_Misc.xml:
- [x] Royalty\DefInjected\HediffDef\Hediffs_Local_Misc.xml:
- [x] Royalty\DefInjected\HediffDef\Hediffs_Psycasts.xml:
- [x] Royalty\DefInjected\HediffDef\WeaponTraitDefs.xml:
- [x] Royalty\DefInjected\IncidentDef\Incidents_Map_Disease.xml:
- [x] Royalty\DefInjected\IncidentDef\Incidents_Map_Misc.xml:
- [x] Royalty\DefInjected\IncidentDef\Incidents_World_Quests.xml:
- [x] Royalty\DefInjected\InteractionDef\Interactions_Social.xml:
- [x] Royalty\DefInjected\JobDef\Jobs_Misc.xml:
- [x] Royalty\DefInjected\MentalStateDef\MentalStates_Special.xml:
- [x] Royalty\DefInjected\PawnKindDef\PawnKinds_Empire.xml:
- [x] Royalty\DefInjected\PawnKindDef\PawnKinds_Refugee.xml:
- [x] Royalty\DefInjected\QuestScriptDef\Script_Bestower.xml:
- [x] Royalty\DefInjected\QuestScriptDef\Script_Hospitality_Refugee.xml:
- [x] Royalty\DefInjected\QuestScriptDef\Script_ShuttleCrash_Rescue.xml:
- [x] Royalty\DefInjected\QuestScriptDef\Scripts_Missions.xml:
- [x] Royalty\DefInjected\QuestScriptDef\Scripts_Permits.xml:
- [x] Royalty\DefInjected\QuestScriptDef\Scripts_ProblemCausers.xml:
- [x] Royalty\DefInjected\ResearchProjectDef\ResearchProjects_Apparel.xml:
- [x] Royalty\DefInjected\RoyalTitlePermitDef\RoyalPermits_Empire.xml:
- [x] Royalty\DefInjected\RulePackDef\RulePacks_Namers_Factions.xml:
- [x] Royalty\DefInjected\RulePackDef\Script_Hospitality_TextCommon.xml:
- [x] Royalty\DefInjected\SitePartDef\MechCluster.xml:
- [x] Royalty\DefInjected\StatDef\Stats_Apparel.xml:
- [x] Royalty\DefInjected\ThingDef\Apparel_Packs.xml:
- [x] Royalty\DefInjected\ThingDef\Apparel_Royal.xml:
- [x] Royalty\DefInjected\ThingDef\Apparel_Various.xml:
- [x] Royalty\DefInjected\ThingDef\Buildings_Exotic.xml:
- [x] Royalty\DefInjected\ThingDef\Buildings_Mech.xml:
- [x] Royalty\DefInjected\ThingDef\Ethereal_Skyfallers.xml:
- [x] Royalty\DefInjected\ThingDef\Ethereal_Various.xml:
- [x] Royalty\DefInjected\ThingDef\Items_Exotic.xml:
- [x] Royalty\DefInjected\ThingDef\Mote_Visual.xml:
- [x] Royalty\DefInjected\ThingDef\PsychicWeapons.xml:
- [x] Royalty\DefInjected\ThoughtDef\Thoughts_Memory_Death.xml:
- [x] Royalty\DefInjected\ThoughtDef\Thoughts_Memory_Misc.xml:
- [x] Royalty\DefInjected\ThoughtDef\Thoughts_Memory_Special.xml:
- [x] Royalty\DefInjected\ThoughtDef\Thoughts_Situation_Special.xml:
- [x] Royalty\DefInjected\ThoughtDef\WeaponTraitDefs.xml:
- [x] Royalty\DefInjected\TipSetDef\Tips.xml:
- [x] Royalty\DefInjected\WeaponTraitDef\WeaponTraitDefs.xml:
- [x] Royalty\DefInjected\WorldObjectDef\WorldObjects.xml:
- [x] Royalty\Keyed\Alerts.xml:
- [x] Royalty\Keyed\Dialog_StatReports.xml:
- [x] Royalty\Keyed\Dialogs_Various.xml:
- [x] Royalty\Keyed\GameplayCommands.xml:
- [x] Royalty\Keyed\ITabs.xml:
- [x] Royalty\Keyed\Letters.xml:
- [x] Royalty\Keyed\MainTabs.xml:
- [x] Royalty\Keyed\Messages.xml:
- [x] Royalty\Keyed\Misc_Gameplay.xml:

**Comment by kiliak** [comment]
voila le gros de la trad est fait ,il faudra une relecture pour les fautes et améliorations...voir les conflits.

2fichiers me posent problème:
![image](https://user-images.githubusercontent.com/40450975/91085114-3daf7280-e64d-11ea-938a-f585d0ff2140.png)
![image](https://user-images.githubusercontent.com/40450975/91085140-46a04400-e64d-11ea-9946-a643f151baa0.png)
je en sais pas pourquoi ils sont dans la liste je ne vois de TODO.

sinon ils reste les TODO dans les fichiers QuestScript et RulePack:
![image](https://user-images.githubusercontent.com/40450975/91085252-751e1f00-e64d-11ea-8486-eb4a04e42fe0.png)
![image](https://user-images.githubusercontent.com/40450975/91085274-7e0ef080-e64d-11ea-9291-45ba865985ec.png)
![image](https://user-images.githubusercontent.com/40450975/91085310-8b2bdf80-e64d-11ea-9a97-70718ac3184d.png)
![image](https://user-images.githubusercontent.com/40450975/91085336-95e67480-e64d-11ea-9037-b5e579dea2ab.png)
je ne suis pas alaise avec la structure de ces fichiers, je vais essayer mais je ne promet rien, habituellement je les laissais aux autres ;)

sinon je ne sais pas comment vous vous y preniez avant mais il doit bien y avoir des textes à modifier en plus des traductions, mais je ne sais pas comment les trouver.

et pour finir il faudra surement relancer une recherche de fichiers a traduire, en général  Ludéon en colle de nouveaux tout au long des mises a jour mineures.

**Comment by ElioNETO-trad** [comment]
Bonsoir,

J'ai essayé de traduire les fichiers qui restent, mais je n'ai pas trop compris comment faut pour les traduire correctement (en ajoutant le genre, le nombre etc).

Du coup je vais étudier un peu plus les codes pour mieux comprendre et je vais essayer ensuite. Je suis ouvert aux conseils aussi!

Elio NETO

**Comment by kiliak** [comment]
Et bien je t'avous que moi aussi j'ai beaucoup de mal avec les fichiers restants 😆. Je ne sais pas trop comment t'expliquer

**Comment by kiliak** [comment]
bon j'aie essayé de finir les derniers fichiers mais je ne ne vois pas comment gérer les possibilité singulier/pluriel dans les règles des RulePack, je pense qu'il faut rajouter des lignes mais c'est hors de mes compétences...ça risque de finir en massacre.

**Comment by kiliak** [comment]
voila c'est fait, a relire
