### ISSUE TITLE
traduction de "bestower"

### ISSUE THREAD

**Issue by kiliak** [Ludeon/RimWorld-fr#330]
plus je regarde moins ça me plait:
bestower traduit en donateur/donatrice

a l'origine c’était parce-que c’était eux  ( faction et bonhomme) qui faisait " cadeau" du titre et pouvoir, mais plus j'y pense et plus je me dit que ça devrait erre remplacé par "émissaire". ça fait plus français a mon sens, même si ce n'est pas la traduction littérale.
un avis?

**Comment by ElioNETO-trad** [comment]
Nous pouvons toujours détacher du sens littéral si cela nous ne convient pas. Je pense que c'est carrément important de suivre l'instinct de "ça fait plus français à mon sens" car comme natif tu peux distinguer ce qui sonne naturel et ce qui sonne pas. Dans mon cas je n'ai pas encore cette sensibilité donc de temps en temps je ne vais pas piéger ces petites distinctions. Si tu me dis qu'émissaire dans ce sens là a l'air d'être plus naturel, je dis qu'il vaut le coup de changer. Cependant nous supprimons toutes les traductions anciennes de "donataire" et nous les remplaçons par "émissaire".

**Comment by kiliak** [comment]
C'est ce que je me dis. ''Donateur'' ne fait vraiment référence qu'a la tâche du pion d'offrirla récompense. D'un point de vue technique et de la traduction littérale c'est bien ça. 
"L'émissaire'' c'est plus l'envoyé de la faction en charge de la représenter auprès de notre colonie et en charge des interactions avec nous.
La différence est subtile mais bien là, du plus à l'oreilles je trouve émissaire plus "Classe" pour une faction qui porte pompeusement le nom d'Empire.

Mais jv'ais attendre la fin de la trad 1.2 dès fois que des avis supplémentaires se fassent connaître

**Comment by ElioNETO-trad** [comment]
Oui, j'ai cherché qu'est ce que voulait dire "bestower" et la traduction littérale fonctionne bien, par contre en français le sens n'a pas la même valeur.

Je viens de mettre à jour la task list avec tous les TODOS à faire (inclus les Def-injected), normalement les documents sont bons pour être traduits !
