### ISSUE TITLE
traduction courte pour Psyfocus et Heat??

### ISSUE THREAD

**Issue by kiliak** [Ludeon/RimWorld-fr#331]
salut, je suis en pleine réflexion sur la réduction des textes là ou ca pose problème, vous auriez une idée pour réduire:
concentration psychique et échauffement neuronal. sur la capture on voit bien que ca ne colle pas.

en anglais c'est Psyfocus et Heat

on a le droit a8 lettre max

![Capture d’écran (11)_LI](https://user-images.githubusercontent.com/40450975/95029507-1666af00-06a9-11eb-9c80-e6eb6ac68ac4.jpg)

**Comment by kiliak** [comment]
j'ai regardé dans les autres langues et beaucoup son dans la même situation que nous et les autres on fait de la traduction littérale"chaleur" et "psyfocus"

de plus pour resté sur le sujet : celons vous, il faudrait changé partout ou juste là (pour contourner ce petit problème de place)????
si on change que là quelqu'un aurait une idée du fichier a changer, j'ai pensé a:
 Core/.../Misc_Gameplay ligne 459
Royalty/.../Misc_Gameplay ligne 49
mais je ne suis pas sur que ce soit les bons

**Comment by b606** [comment]
"Psyfocus" Je pense qu'il ne faut changer que là en vérifiant dans le jeu si c'est L49 ` <Psyfocus>` ou L51 `<PsyfocusLabelGizmo>`. On a mis concentration psychique partout (42 fois) sauf quand on a mis **focalisation psychique** (3x).  Il y a les textes des tooltips en mettant la souris sur la barre de niveau.

Pour "Échauffement" on pourrait juste mettre ""Échauff." puisque le tooltip l'explique.

https://github.com/Ludeon/RimWorld-fr/blob/38c1cab17d533df94c1a9d7eac95a164835ee31e/Royalty/Keyed/Misc_Gameplay.xml#L86-L89

https://github.com/Ludeon/RimWorld-fr/blob/38c1cab17d533df94c1a9d7eac95a164835ee31e/Core/Keyed/Dialogs_Various.xml#L1029-L1030

https://github.com/Ludeon/RimWorld-fr/blob/38c1cab17d533df94c1a9d7eac95a164835ee31e/Royalty/Keyed/Alerts.xml#L50-L51

**Comment by b606** [comment]
PS: `<PsyfocusCostPerMentalBreakIntensity>` dans RimWorld-fr/Core/Keyed/Dialogs_Various.xml
- Dans quelle condition ce texte s'affiche-t-il ?
- "rupture mentale" devrait être "crise de nerfs", "crise de démence" ou "dépression"

**Comment by b606** [comment]
Corrigé dans le dernier commit.
A+ :smiley:
