### ISSUE TITLE
Traduction de <ClickToJumpToFlashstorm>

### ISSUE THREAD

**Issue by b606** [Ludeon/RimWorld-fr#332]
Il me semble y avoir une erreur de traduction ici mais je n'arrive pas à trouver ce texte dans le jeu : 

https://github.com/Ludeon/RimWorld-fr/blob/9ceb833e91c35c9eeee92ed9204cdab85523dc61/Core/Keyed/Misc_Gameplay.xml#L954

Est-ce que çà ne devrait pas être : 

```
  <!-- EN: Click to jump to the flashstorm. -->
  <ClickToJumpToFlashstorm>Cliquez pour **aller à** la tempête d'éclairs.</ClickToJumpToFlashstorm>
```

**Comment by kiliak** [comment]
effectivement dans les autres langue ca a été traduit par quelque chose dans ce sens: "Cliquez pour accéder à l'emplacement de la tempête éclair"

**Comment by b606** [comment]
Corrigé !
