### ISSUE TITLE
"Randomiser"

### ISSUE THREAD

**Issue by JGoutin** [Ludeon/RimWorld-fr#374]
Bonjour,

Le mot "Randomiser" n'existe pas en français: c'est un anglicisme.

Les mots "Régénérer" ou "Relancer" seraient plus adaptés.

Le mot est présent aux endroits suivants:
https://github.com/Ludeon/RimWorld-fr/blob/master/Core/Keyed/Menus_Main.xml#L542
https://github.com/Ludeon/RimWorld-fr/blob/master/Core/DefInjected/InstructionDef/Instructions.xml#L173
https://github.com/Ludeon/RimWorld-fr/blob/master/Core/DefInjected/InstructionDef/Instructions.xml#L175

**Comment by BlastCom** [comment]
Si tu veux, tu peux rejoindre le discord de la traduction française pour démarrer une discussion avec la communauté.
Le lien est dans le README.md

**Comment by kiliak** [comment]
Je propose: Aleatoire

**Comment by BlastCom** [comment]
C'est commit :)
On a garder l'harmonisation pour aléatoire, puisqu'il était déjà utiliser dans fichier.

Ici : https://github.com/Ludeon/RimWorld-fr/commit/8937b2f88b0788cf20b69fd56db6ec8b18ea34a4
